### ISSUE TITLE
Project jumps out of view while editing

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/skills#128]
Given I have a list of existing projects, more than fit on one height of my screen, and given I edit a project with the end date "today" ("heute").
When I change the end date month dropdown from "heute" to "-" in order to enter a year,
Then the project jumps to the bottom of the page, out of view, appearing to have vanished.
Expected: The project always stays in view while I am in edit mode. Either it doesn't move, or the screen should scroll to follow it automatically.

**Comment by Robin481** [comment]
Behoben mit Release 4.1.0: https://github.com/puzzle/skills/releases/tag/v4.1.0
