### ISSUE TITLE
Search for fields other than person name

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/skills#129]
I would like to search for e.g. all people that have done something with e.g. Angular, or that mention RedHat somewhere in their Skills page. Currently, I can only search people by name.
Search should include the following fields:
* Name
* Abschluss
* Funktion
* Firma / Kategorie
* Kernkompetenzen
* Ausbildung:
  * Ausbildung
  * Ausbildungsort
* Weiterbildung:
  * Beschreibung
* Stationen
  * Rolle
  * Firmenangaben und Beschreibung der Tätigkeit
* Projekte
  * Projekt
  * Beschreibung
  * Rolle und Aufgaben
  * Eingesetzte Technologien
* Fachwissensskala (once that feature is implemented)

**Comment by odaner** [comment]
hey @carlobeltrame check https://github.com/puzzle/skills/issues/182

**Comment by odaner** [comment]
we re-deployed the search-feature today on production.
