### ISSUE TITLE
FavIcon macht Verbindung "nicht sicher"

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#130]
Wegen des FavIcons erscheint im Browser eine Sicherheitswarnung. Nicht kritsich, aber etwas unschön.
![tooltip_688](https://user-images.githubusercontent.com/15013947/52219308-ad5be200-289c-11e9-9ddb-1da43e8f8436.png)
![auswahl_687](https://user-images.githubusercontent.com/15013947/52219314-af25a580-289c-11e9-8c68-42670df78f76.png)

**Comment by nerrehmit** [comment]
I think this MR https://github.com/puzzle/skills/pull/152/files fixes this error. 
currently there is a broken link to the favicon. Therefore it is not loaded and creates mixed (http/ https) content.

**Comment by Robin481** [comment]
@nerrehmit This is correct, we have merged this, but are waiting for our Version 4.1.0 Release to close this issue. Thanks for your input.

**Comment by Robin481** [comment]
Behoben mit Release 4.1.0: https://github.com/puzzle/skills/releases/tag/v4.1.0
