### ISSUE TITLE
Fehlervalidierung bevor User etwas eingegeben hat

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#133]
Wenn ich die Seite aufrufe, werden die beiden Inputfelder bereits rot markiert, weil sie leer sind:
![grafik](https://user-images.githubusercontent.com/7139459/52465488-0ff3fd00-2b7f-11e9-8c18-ca0ea3b56b58.png)

Das teilt dem User mit, dass er bereits einen Fehler gemacht hat, noch bevor er überhaupt irgendetwas gemacht hat. :) 

Ich würde diese Instantvalidierung komplett weglassen, weil solche Loginseiten bestens bekannt sind.

**Comment by odaner** [comment]
jep, valides issue, werden wir fixen.

**Comment by Robin481** [comment]
Behoben mit Release 4.1.0: https://github.com/puzzle/skills/releases/tag/v4.1.0
