### ISSUE TITLE
Navigation unklar

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#135]
Wenn ich in der Hauptnavigation "Firmenprofile" wähle, muss ich als nächstes eine von vier Submenupunkten wählen. Habe ich beispielsweise "Puzzle ITC" gewählt, sehe ich den gewählten Pfad nicht, besonders wenn ich alle Akkordeons eingeklappt habe:
![grafik](https://user-images.githubusercontent.com/7139459/52465969-e76d0280-2b80-11e9-9645-fcbf88174d39.png)

Ein Breadcrumb könnte hier helfen. Z.B. so:
![grafik](https://user-images.githubusercontent.com/7139459/52466092-65c9a480-2b81-11e9-9bb6-ae39f0d9b751.png)

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta.Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
 Breadcrumb macht hier aber sicher viel Sinn.
