### ISSUE TITLE
Buttontext nicht lesbar

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#136]
Habe einen Buttontext gefunden, der nicht ganz angezeigt wird:
![grafik](https://user-images.githubusercontent.com/7139459/52466140-99a4ca00-2b81-11e9-81a6-fa54226942ed.png)

Vielleicht gibt es noch mehr solche?

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
