### ISSUE TITLE
Unklares Speicherverhalten

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#137]
Wenn ich Akkordeons bearbeite und neue Inhalte hinzufüge, kann ich in der Hauptnavigation an einen anderen Ort wechseln und die Daten werden trotzdem und ohne Information gespeichert. 
![grafik](https://user-images.githubusercontent.com/7139459/52466305-36fffe00-2b82-11e9-98ed-adebb0ac6217.png)

Das ist nicht meine Erwartung, wenn ich ein Save-Icon sehe:
![grafik](https://user-images.githubusercontent.com/7139459/52466300-323b4a00-2b82-11e9-9531-ac802d084b03.png)

Meine Erwartung beim Wegnavigieren wäre, dass mich PuzzleSkills fragt, ob ich wirklich wegnavigieren möchte, weil sonst meine Änderungen verworfen werden.

**Comment by Robin481** [comment]
Die Daten werden nicht wirklich gespeichert aber in den Cache geschrieben. Nach einem Neuladen der Seite sind sie weg. 
Beim Abbruch werden diese in den Cache geschriebenen Daten rausgelöscht, beim Verlassen der Seite aber nocht nicht, wir werden dies abklären.

Eine Bestätigung vor dem Verlassen der Seite macht aber sicher Sinn, ich werde es mit Ändu besprechen.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
