### ISSUE TITLE
Buttons "Unbekannt"

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#138]
Ich verstehe die Spalte neben den Ex-Mitarbeitenden nicht, welche lediglich Buttons "Unbekannt" enthält:
![grafik](https://user-images.githubusercontent.com/7139459/52466477-a970de00-2b82-11e9-810d-67b563babc09.png)

Was ist das? Warum sind die dort? Würde ein Spaltenlabel helfen?

**Comment by Robin481** [comment]
Diese Spalte zeigt den Abschluss der jeweiligen Personen an, da wir es von den Ex-Mitarbeitern meistens nicht wissen sind sie leider öfters unbekannt.

Label wird hinzugefügt.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
