### ISSUE TITLE
Kaputtes Edit Layout

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#139]
So sieht es aus, wenn ich eine neue Adresse hinzufügen möchte:
![grafik](https://user-images.githubusercontent.com/7139459/52466613-2a2fda00-2b83-11e9-8639-9dd23066d630.png)

Wäre toll, wenn das Löschen-Icon nicht über das Inputfeld kommen würde.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
