### ISSUE TITLE
Unklare Action "Neue Firma"

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#140]
Für mich ist nicht ganz klar, was die Aktion" Neue Firma" genau macht, bzw. wo genau diese Aktion einen Eintrag hinzufügt:
![grafik](https://user-images.githubusercontent.com/7139459/52466703-7e3abe80-2b83-11e9-8586-6d87a8e283ab.png)

Ich gehe davon aus, dass es sich um die Liste unserer vier Firmenprofile handelt. Bin aber verwirrt, weil wir dort einen Eintrag "Partner" haben. 

Mir würde es helfen, wenn die Aktion "Firmenprofil hinzufügen" heissen würde. Dann würde ich die Aktion mit der Firmenprofile-Liste assoziieren und nachvollziehen können, dass man hier irgendwelche Einträge hinzufügen kann, z.B. "Meine eigene Liste". Und nicht zwingend eine Firma.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.
