### ISSUE TITLE
Lustiges Verhalten beim Löschen von Einträgen

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#141]
Wenn ich ein Profil löschen möchte, wandert der Button "Profil löschen" im Hintergrund aus dem Layout raus:

![grafik](https://user-images.githubusercontent.com/7139459/52466893-0f119a00-2b84-11e9-9f54-3f81969086a1.png)

Nur eine Kleinigkeit, aber halt trotzdem irgendwie unschön.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Mir ist aber gerade nicht ganz klar, was du damit meinst: 
"...wandert der Button "Profil löschen" im Hintergrund aus dem Layout raus:"

**Comment by Robin481** [comment]
Wir haben ziemlich lang versucht diesen Fehler zu fixen aber er hält sich ziemlich hartnäckig. 
Da es meiner Meinung nach nicht ein Breaking-Issue habe ich es für den Moment auf "on hold" getan.
Ein neues Ticket wurde erstellt und in den Backlog aufgenommen, falls dann Bedarf entsteht können wir dies wieder aufnehmen.

**Comment by Joshuasony** [comment]
Ja, ist überhaupt nicht tragisch. Nur unschön, aber sicht nicht kritisch.
