### ISSUE TITLE
Unklares Interaktionspattern

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#142]
Im Akkordeon "Angebot" bei den Firmenprofilen unter "Ex-Mitarbeiter" sehe ich ein grosses Inputfeld:
![grafik](https://user-images.githubusercontent.com/7139459/52467160-d3c39b00-2b84-11e9-999a-54aa203dccb8.png)

Das hat für mich den Aufforderungscharakter eines Inputfeldes, das ich direkt bearbeiten kann.

Ich kann draufklicken und sehe dann einen blauen Rahmen (aber keinen Cursor):
![grafik](https://user-images.githubusercontent.com/7139459/52467204-f1910000-2b84-11e9-99b4-5284f33ea7df.png)

Das Feld ist also irgendwie im Fokus, ich kann aber trotzdem nicht bearbeiten.

Das Inputfeld ist für mich irreführend, weil ich meine, dass ich Änderungen direkt vornehmen kann. 

**Vorschlag:**
- Entweder öffnet der Klick auf das Inputfeld direkt den Bearbeitungsmodus (unpraktisch, wenn man Text kopieren möchte)
- Oder man stellt die Information anders dar, z.B. ohne Rahmen, so wie ihr es hier macht:
![grafik](https://user-images.githubusercontent.com/7139459/52467296-551b2d80-2b85-11e9-9f31-d2db7729f2ff.png)

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.

**Comment by odaner** [comment]
Hi Josh, wir werden das Feature Firmenprofile vorerst nicht weiterverfolgen. Daher setze ich das Issue auf "Wontfix" und "Closed". Aber trotzdem merci nochmals fürs Feedback!
