### ISSUE TITLE
Aktion "Neues Profil" klarer machen

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#143]
Wenn ich mich in einem Firmenprofil befinde und eine neue Person erfassen muss, finde ich zuunterst in der Liste des Akkordeons "Profile" den Button mit dem Text "Neues Profil". 
![grafik](https://user-images.githubusercontent.com/7139459/52467489-015d1400-2b86-11e9-9182-975eced29b33.png)

Wenn ich diesen Button klicke, gelange ich in der Hauptnavigation zum Hauptnavigationspunkt "Person" auf der Seite mit dem Titel "Person erfassen".
![grafik](https://user-images.githubusercontent.com/7139459/52467498-0ae67c00-2b86-11e9-83c0-da1e33d7df66.png)

Mir würde es helfen, wenn der Button so heissen würde, wie die Seite, auf der ich lande, also "Person erfassen" oder "Neue Person erfassen". Dann ist auch sofort klar, dass ich eine Person erfasse und nicht ein "Firmenprofil".

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.

**Comment by odaner** [comment]
Hi Josh, wir werden das Feature Firmenprofile vorerst nicht weiterverfolgen. Daher setze ich das Issue auf "Wontfix" und "Closed". Aber trotzdem merci nochmals fürs Feedback!
