### ISSUE TITLE
Durchgängiges Form Design

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#144]
Aktuell unterscheiden sich das Styling der Inputfelder:
![grafik](https://user-images.githubusercontent.com/7139459/52467682-a8da4680-2b86-11e9-8697-1acd4ae7b276.png)

Wäre toll, wenn das überall gleich wäre.

**Comment by odaner** [comment]
Hi Josh, merci für das Issue. Das Feature der "Firmenprofile" ist aktuell eh noch ziemlich Beta. Wir wollen hier primär herausfinden, ob das wirklich ein Need ist bevor wir hier noch weiter optimieren. Aktuell haben andere Features Priorität.

**Comment by odaner** [comment]
Hi Josh, wir werden das Feature Firmenprofile vorerst nicht weiterverfolgen. Daher setze ich das Issue auf "Wontfix" und "Closed". Aber trotzdem merci nochmals fürs Feedback!
