### ISSUE TITLE
Aktion "Neues Profil": Feldvalidierungen & Fehler beim Speichern dem Benutzer anzeigen

### ISSUE THREAD

**Issue by guesche** [puzzle/skills#150]
Ausgangslage: -Login und auf der Startseite wird 'Neues Profil' gewähl -> Navigation auf "https://skills.puzzle.ch/people/new"

Beobachtetes Verhalten:
-Es werden ein- oder mehrere Felder nicht ausgefüllt z.Bsp. "Abschluss" und "Geburtsdatum"
-Button "Speichern" wird betätigt
-Vom Server wird ein HTTP StatusCode 422 zurückgegeben, der Benutzer merkt jedoch nichts davon

Erwartetes Verhalten:
-Feldvalidierungen im UI sichtbar machen und/oder zumindest ein Errorhandling seitens UI einbauen, damit Backenderrors dem Benutzer mitgeteilt werden

**Comment by Robin481** [comment]
Hierbei scheint es sich um einen Bug zu handeln denn Error messages für "new-profile" sind bereits implementiert aber scheinen im Moment nicht zu funktionieren.
Werden wir anschauen, danke für die Meldung.

**Comment by Robin481** [comment]
Behoben mit Release 4.1.0: https://github.com/puzzle/skills/releases/tag/v4.1.0
