### ISSUE TITLE
Aktion .odt exportieren: "Zusammenfassung Kernkompetenzen" mit unerwünschten Aufzählungszeichen

### ISSUE THREAD

**Issue by guesche** [puzzle/skills#151]
Ausgangslage: -odt export eines CVs wird erstellt.

Beobachtetes Verhalten:
-Sämtliche Zeilen "Kernkompetenzen" des WebGUI's werden in der exportierten .odt Datei Kapitel 2 "Zusammenfassung Kernkompetenzen" mit Aufzählungszeichen versehen. Selbst wenn es sich bei den Zeilen um Leerzeilen handelt. Dies erfordert danach eine manuelle Korrektur.

Erwartetes Verhalten:
-Variante1: Leerzeilen im WebUI Feld "Kernkompetenzen" ergeben im .odt Kapitel 2 "Zusammenfassung Kernkompetenzen" keine Aufzählungszeichen
-Variante2: keine Zeile des Freitextfeldes "Kernkompetenz" im WebUI erhält im exportierten .odt automatisch Aufzählungszeichen und der Freitext wird, wie im Webgui erfasst, ins Kapitel 2 "Zusammenfassung Kernkompetenzen" übernommen. 
=> PO soll entscheiden

**Comment by odaner** [comment]
Das beste für den Moment wäre es, die Variante 2 umzusetzen. Es braucht imho so oder so immer eine gewisse nach-Formatierung. Und im Zusammenhang mit dem Skill-Management wird der Bereich Kernkompetenzen dann so oder so überarbeitet. @ team könnt ihr V2 angehen bitte?

**Comment by mzurbuchen** [comment]
https://github.com/puzzle/skills/commit/2aab7b4cd63c0922980f608db31d68963bd99bd0
