### ISSUE TITLE
Sprachen-Zertifikate im CV-Template nicht als separate Spalte

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#169]
Es wäre gut, wenn die Sprachen-Zertifikate im CV-Template nicht in einer separeten Spalte sind, sondern hinten an den Level angehängt werden.
Also etwa so:

[LEVEL] { / Zertifikat: [CERTIFICATE]}

sprich: sofern ein Zertifikat vorhanden ist, wird ein Label " / Zertifikat: " sowie das [CERTIFICATE] eingefügt.

**Comment by Robin481** [comment]
@odaner Wird im nächsten Sprint gemacht.
