### ISSUE TITLE
fix ember tests

### ISSUE THREAD

**Issue by psunix** [puzzle/skills#17]
run ember test in frontend folder and fix all failing tests

**Comment by SamuelSchwegler** [comment]
Bei mir scheitern die acceptance Tests, sie verändern alle die Datenbank so dass ein Test den nächsten zum failen bringt.
Bsp: Test 1 sucht Mitarbeiter Bob Anderson und benennt ihn um in Hansjoggeli. Test 2 sucht nun wieder Bob Anderson, der Existiert aber nicht mehr sondern Hansjoggeli.

Ich denke das sollte nicht so sein weis aber noch keine Lösung.

**Comment by psunix** [comment]
das README im frontend folder stimmt nicht ganz.
die frontend tests müssen via `rake spec:frontend` ausgeführt werden. Wenn ich das so mache laufen alle tests durch. Steht so im haupt-README.md. kannst du das evtl. noch so anpassen im frontend readme? man könnte `ember test` vermutlich noch so anpassen das die acceptance tests nicht ausgeführt werden.

**Comment by SamuelSchwegler** [comment]
Besten Dank. `rake spec:frontend:serve` funktioniert. Aber bei `rake spec:frontend` kriege ich folgenden Fehler:  
`rake spec:frontend
bin/frontend-tests.sh
=> Booting Puma
=> Rails 5.1.4 application starting in test 
=> Run `rails server -h` for more startup options
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /home/samuel/Schreibtisch/INFO/4_PSE/code/skills/config/initializers/new_framework_defaults.rb:15)
ERROR: [Errno 2] No such file or directory: 'test'
rake aborted!
Command failed with status (1): [bin/frontend-tests.sh...]
/home/samuel/Schreibtisch/INFO/4_PSE/code/skills/lib/tasks/frontend.rake:18:in `block (2 levels) in <top (required)>'
/home/samuel/.rvm/gems/ruby-2.2.9/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/samuel/.rvm/gems/ruby-2.2.9/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => spec:frontend`
Daraus werde ich nicht sonderlich schlau.

**Comment by psunix** [comment]
bei mir laufen die tests durch. 
es steht ja was von no such file or directory 'test'

https://github.com/puzzle/skills/blob/master/bin/frontend-tests.sh

eigentlich wird dieses script dann ausgeführt. schau mal ob du es debuggen kannst.

**Comment by SamuelSchwegler** [comment]
Dann handelt es sich wohl um ein lokales Problem deshalb werde nun ein pull request machen.
