### ISSUE TITLE
Anzeige von Sub-Titel Labels "Projekte" im CV-Template

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#171]
Ich möchte gerne im CV-template die "Sub-Titel" in den Projekten mitgeben.

Der Projekttitel soll dabei auch neu Formatiert werden

![Auswahl_728](https://user-images.githubusercontent.com/15013947/54347257-f266f700-4646-11e9-9445-4abad2dc1c09.png)

[Projekttitel]  (Roboto 10.5)

[Projektbeschreibung] (Roboto 10)
[hier die Inhalte] (Roboto Light 10)

[Rolle und Aufgaben im Projekt] (Roboto 10)
[hier die Inhalte] (Roboto Light 10)

[Eingesetzte Technologien und Methoden] (Roboto 10)
[hier die Inhalte] (Roboto Light 10)

**Comment by Robin481** [comment]
@odaner Wird im nächsten Sprint gemacht.
