### ISSUE TITLE
Bug bei Profilwechsel wenn Edit-Mode aktiv

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#172]
Wenn ich bei Ausbildung, Weiterbildung oder Stationen im aktiven Edit Mode bin und dann das Profil wechsle, wird der Edit-Mode nich abgebrochen, beim neue ausgewählen Profil werden dann die Daten des vorherigen Profils im Edit-Mode übernommen. Sehr unschön, bitte rasch fixen

**Comment by Robin481** [comment]
@odaner Wird gemacht.

**Comment by Robin481** [comment]
#178 
In Progress
