### ISSUE TITLE
Reihenfolge der "Kapitel" im CV-Output (Template) anpassen

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#179]
Habe von Jonas Probst den Input erhalten, die Reihenfolge der Kapitel im CV-Output (Template) anzupassen.

Reihenfolge heute: 
1    Personalien
2    Sprachkenntnisse
3    Zusammenfassung Kernkompetenzen
4    Ausbildung
5    Weiterbildung (Schulungen, Kurse, Konferenzen, Referate)
6    Stationen
7    Projekte

Reihenfolge **VORSCHLAG**: 
1    Personalien
2    Zusammenfassung Kernkompetenzen
3    Projekte
4    Stationen
5    Ausbildung
6    Weiterbildung (Schulungen, Kurse, Konferenzen, Referate)
7    Sprachkenntnisse

Bitte Up/Downvote. Bei Down, macht doch als Comment einen anderen Vorschlag :-)

**Comment by Robin481** [comment]
- Ich denke wenn Sprachkenntnisse zuunterst ist geht es ein wenig verloren da es meistens auch nur eine kleine Tabelle ist. Vielleicht könnte man es geschickt mit der Personalien Tabelle kombinieren.
- Es würde vermutlich Sinn machen die Reihenfolge auf der Website und dem Export gleich zu halten. Was ist die Idee hinter der vorgeschlagenen Reihenfolge? -> Würde diese Reihenfolge auch Sinn auf der Website machen?

**Comment by odaner** [comment]
- hmm Kombination mit Personalien wäre eine Möglichkeit. Für einen "Quick-Win" wäre es am Ende imho optimaler, da sehr einfach umzusetzen. Und: Sprache ist halt für den Kunden oft am wenigsten wichtig, da gebe ich JP recht.

- Nein ich denke auf der Website ist die Reihenfolge Okey. Resp. dort sind ja einerseits die Sprachen Teil der Personalien. Andererseits macht die (lange) Liste der Projekte am Schluss recht viel Sinn für Leute die doch eher scrollen anstatt die Seiten-Navigation zu verwenden.
Sprich: Website hat Fokus auf den User (Member), Output hat Fokus auf den Kunden (Marketing-Perspektive)

**Comment by jonasprobst** [comment]
Ich finde "Profil" besser als "Zusammenfassung Kernkompetenzen" - mindestens einfach auf "Kernkompetenzen" reduzieren. Auch würde ich das eher in Textform sehen als eine Auflistung von ein paar Technologien. Da könnten dann auch Softskill mit einfliessen.

**Comment by kallies** [comment]
IMO kann "Weiterbildung (Schulungen, Kurse, Konferenzen, Referate)" vor "Ausbildung" stehen.

**Comment by guesche** [comment]
- Die Sprachkenntnisse finde im neuen Export generell zu prominent mit dieser Tabelle, fand ich im alten CV Tool besser
-Zu der Reihenfolge: in einem CV würde ich persönlich die Projekte am Ende belassen, da diese Liste 'unendlich' lange sein kann und das Lesen bzw. den Überblick über die weiteren Punkte erschwert
-Generell würde ich auch schauen, wenn man etwas an der Reihenfolge ändert, diese im exportierten CV und online gleich ist.

**Comment by odaner** [comment]
Wir werden nun folgende Anpassungen vornehmen und testen, wie sich das bewährt:

1    Personalien
2    Kernkompetenzen (anstatt "Zusammenfassung..:"
3    Stationen
4    Projekte
5    Weiterbildung (Schulungen, Kurse, Konferenzen, Referate)
6    Ausbildung
7    Sprachkenntnisse

Wenn es für spezifische Cases überhaupt nicht stimmt, kann die Reihenfolge ja rasch angepasst werden im .odt

Wenn sich diese Reihenfolge bewährt, werden wir schauen dass wir dieselbe auch im Tool umsetzen.

@guesche wir nehmen jetzt die Projekte trotzdem rauf, ist in CVs (Exports) halt schon "Best Practice" dass diese weit oben aufgeführt werden, da für die Leser nebst den Stationen am relevantesten. Hoffe du kannst dich damit anfreunden ;-)

**Comment by odaner** [comment]
Neues CV wurde heute produktiv deployed. Wenn sich diese Reihenfolge bewährt, werden wir schauen dass wir dieselbe auch im Tool umsetzen.
