### ISSUE TITLE
CV-Durchsuchen als Workaround wieder einbauen

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#182]
Mit der Einführung des neuen Suchfelds für CVs werden nur noch die Profile (Members) gesucht. Dies ist dank des "Typeaheads" sehr praktisch, aber es such eben nur noch die Members.

In der CV-Tool Suche wurde eine Volltextsuche über alle Inhalte des CVs durchgeführt. Als Resultat wurde die Members-Liste links nach den "Treffern" gefiltert.

Die "Durchsuchen" Funktion wird von vielen Usern vermisst. Wir sollten diese ASAP wieder zur Verfügung stellen. Daher bitte folgendes mit Prio 1 nächste Woche in den Sprint aufnehmen:

- Die "CV-Durchsuchen"-Funktion aus dem CV-Tool als separates Menu-Item "Suche" wieder anbieten
- Im Suchfeld ein hint "CV Durchsuchen ..." einblenden
- Unterhalb gibt es den Bereich "Suchresultate". Sofern keine Suche erfolgt ist oder eine durchgeführte Suche keine Treffer ergab, das Label "Keine Resultate" anzeigen
- Wenn Treffer gelandet werden, die Vor- und Nachnamen der Members in Form von "Pills" resp. "Tags" anzeigen
- Sortierung ist nach ABC nach Vornamen
- Farben siehe Mockup
- Mit Klick auf das "Tag" gelange ich auf den CV des Members
- Ich kann im Suchfeld die Suche mit Klick auf "x" löschen

WEITER:
Bitte den Menupunkt "Firmenprofile" aus der Navigation entfernen. Die Tests haben gezeigt, dass dieses Feature aktuell nicht wirklich benötigt werden. Es lohnt sich nicht, hier aktuell weiterzuarbeiten. Daher kann der Link in der Navigation entfernt werden.
Ich werde dann noch alle Issues zum Firmenprofil mach "closen".

Priorität hat nun dieser Workaround und dann wie gewohnt gemäss Roadmap die Umsetzung des Skill-Management Features. Solbald dieses umgesetzt ist und die neue Suche zur Verfügung steht, kann der Workaround auch wieder entfernt werden.

![SkillSucheWorkaround](https://user-images.githubusercontent.com/15013947/55412886-86522180-5568-11e9-8947-8fc7a94b693d.png)

**Comment by Robin481** [comment]
#195

**Comment by odaner** [comment]
Wurde heute produktiv deployed.
