### ISSUE TITLE
Erweiterung Fachwissensskala/Skills um Branchen-/Fachwissen

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#190]
Reported von SP: 
**Ausgangslage / Ist-Situation**
Im Rahmen des Digitalisierungsprojekts wurde festgestellt, dass wir vor allem Branchen- und Fach-Know-How von Members zu wenig nutzen um neue Geschäftsfelder oder Branchen zu erschliessen.

**Soll-Situation**
Die Verantwortlichen für die P31, P11 und P15 Prozesse stellen sicher, dass Internes Member Know-How respektive Fachwissen besser genutzt wird um allenfalls neue Geschäftsfelder oder Branchen zu erschliessen oder das Angebot darauf auszurichten.

**Input resp. Lösungsvorschlag von AR:**
Ich schlage vor, dass wir hier in einem ersten Schritt überhaupt erst das Fachwissen strukturiert erfassen. Dies durch Erweiterung der Fachwissenskala um eine neue Kategorie “Branchenwissen”. Dazu müsste das CV Tool wohl erweitert werden, damit der Benutzer selbst neue Einträge zu einer Kategorie erfassen könnte.

**Comment by odaner** [comment]
Ich als PO stehe diesem Punkt eher skeptisch gegenüber.
Was denkt die Community dazu?

**Comment by jonasprobst** [comment]
Geht das nicht aus den Projekten hervor?

**Comment by kallies** [comment]
Ich finde es gut, das Attribut zur Verfügung zu haben um danach auch filtern/suchen zu können. Im CV muss das schlussendlich nicht verfügbar sein.

**Comment by odaner** [comment]
> Geht das nicht aus den Projekten hervor?

Sehe ich auch so...

**Comment by Robin481** [comment]
Projekte sollen hier für den Moment reichen, sonst bitte wieder melden wenn es neue Ideen gibt :)
