### ISSUE TITLE
Aktion "CV Export" in Sidebar-Navigation

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#203]
Für eine bessere Usability, bitte die Aktion "CV Export" in der Sidebar-Navigation gem. Mockup hinzufügen. 

Das Icon dann bitte auch blau verwenden, habe auf die Schnelle grad nur das schwarze Icon gehabt.

![CV-Export-Sidebar](https://user-images.githubusercontent.com/15013947/56891215-0c845980-6a7c-11e9-9a48-7d9f6bf0e28f.png)

**Comment by TheWalkingLeek** [comment]
> Für eine bessere Usability, bitte die Aktion "CV Export" in der Sidebar-Navigation gem. Mockup hinzufügen.
> 
> Das Icon dann bitte auch blau verwenden, habe auf die Schnelle grad nur das schwarze Icon gehabt.
> 
> ![CV-Export-Sidebar](https://user-images.githubusercontent.com/15013947/56891215-0c845980-6a7c-11e9-9a48-7d9f6bf0e28f.png)

Soll denn der ursprüngliche Export Button noch bleiben? Oder soll dieser entfernt werden?

**Comment by odaner** [comment]
Der ursprüngliche Button kann bleiben.
