### ISSUE TITLE
Neue Skill-Suche

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#229]
Zusätzlich zur CV-Suche (bitte Label in Navigation anpassen) gibt es neu eine Skill-Suche.

Hier können Skills gesucht werden die in der Skill-DB vorhanden sind. Es kann jedoch immer nur 1 Skill gesucht werden.

Unten werden dann die Members angezeigt, welche diesen Skill bewertet haben.

Die Namen der Members sind Links auf die Profile (Skills-Screen).

Screen 1: Einstieg
![Skill-Suche-page-1](https://user-images.githubusercontent.com/15013947/59043812-3dc32700-887d-11e9-8b8e-45ab7ee5bb0d.png)

Screen 2: Suche
![Skill-Suche-page-2](https://user-images.githubusercontent.com/15013947/59043856-4c114300-887d-11e9-8b7b-fd18b840d8f5.png)

Screen 3: Resultate
![Skill-Suche-Page 3](https://user-images.githubusercontent.com/15013947/59043872-559aab00-887d-11e9-96ac-d1f7eeffc801.png)

**Comment by Robin481** [comment]
#235

**Comment by Robin481** [comment]
In Master gemerged
