### ISSUE TITLE
Profil-Link zeigt auf falsche Seite

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#240]
Wenn ich mir anschaue, welche Profile einen entsprechenden Skill habe (im SkillSet und zukünftig auch in der Skill-Suche), dann kann ich aufs Profil klicken. Ich gelange dann aber auf den CV des Members, jedoch sollte der Link auf die Skill zeigen.

Zudem wäre es in der Skillset Tabelle sinnvoll, den Skill als Hyperlink anzuzeigen (blaue Font).

![Auswahl_862](https://user-images.githubusercontent.com/15013947/59760675-216ab580-9293-11e9-97c7-b5bd05197adf.png)

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/259

**Comment by odaner** [comment]
Noch nicht gut, zeigt immer noch auf CV, nicht auf Skills-Tab.
