### ISSUE TITLE
Sticky Bereiche in Fenstern

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#241]
Es wäre wirklich extrem hilfreich, wenn wir grössere Bereiche des Fenster "sticky" machen können (Fokus auf Chrome & Firefox latest):

Die "Sticky-Bereiche" sind gelb markiert.

**Profile (CV, Skills)**
![Auswahl_864](https://user-images.githubusercontent.com/15013947/59761017-f9c81d00-9293-11e9-8311-473d570ad12c.png)

**CV Suche**
![Auswahl_865](https://user-images.githubusercontent.com/15013947/59761037-03ea1b80-9294-11e9-9f85-5cb0b9ae9deb.png)

**Skillset**
![Auswahl_866](https://user-images.githubusercontent.com/15013947/59761055-182e1880-9294-11e9-9a30-8d92c0180b19.png)

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/267
