### ISSUE TITLE
Suchbegriff verschwindet aus Suchfeld im Skillset

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#243]
Der erfasste Suchbegriff (hier "Alef") im Suchfeld beim Skillset verschwindet, wenn ich gesucht habe, und dann einen anderen Screen aufrufe, und wieder zurück aufs skillset gehe. Die Suche ist zwar noch vorhanden, aber ich kann sie nicht wirklich sehen oder auch löschen/zurücksetzen.

![Auswahl_871](https://user-images.githubusercontent.com/15013947/59763087-0ac75d00-9299-11e9-9357-9796344a72c5.png)

Beim Suchfeld der CV-Suche funktioniert das. Dort ist es aber eine andere Art Suchfeld. Bitte bei der CV-Suche und der Skill-Suche im Skillset die gleiche Art Suchfeld verwenden.

![grafik](https://user-images.githubusercontent.com/15013947/59763133-32b6c080-9299-11e9-84f6-f8537fb61f92.png)

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/261
