### ISSUE TITLE
Loading-Spinner für "Neue Skills zur Bewertung"

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#244]
Wenn ich auf den Skills-Tab wechsle, dauert es immer einen Moment bis die "Neue Skills zur Bewertung" geladen und angezeigt werden. Dem User wird aber nicht angezeigt, dass hier etwas geladen wird.

Daher bitte einen Loading-Spinner mit einer entsprechenden Meldung anzeigen (Neue Skills zur Bewertung werden gesucht..."

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/261
Merged in Master
