### ISSUE TITLE
Ausrichtung der Daten "von - bis" im CV

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#246]
Im CV bitte die Daten "von - bis" oben ausrichten. So, dass sie immer auf derselben Höhe wie die 1. Zeile der Einträge sind.

Gilt für:
- Ausbildung
- Weiterbildung
- Stationen

![Auswahl_874](https://user-images.githubusercontent.com/15013947/59845403-a1f5e880-935d-11e9-8502-80e587c48bd2.png)

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/263

Persönlich finde ich es jetzt nicht so schön :sweat_smile: 
![image](https://user-images.githubusercontent.com/32168247/60323780-5c4fa600-9983-11e9-9c28-2315a076d0ac.png)

**Comment by odaner** [comment]
ich finds sehr okey so. Vorher hatte es einfach eine falsche Ausrichtung, daher wirkt das so nun viel aufgeräumter :-)
