### ISSUE TITLE
Styleing Sidebar-Navigation

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#247]
Die Sidebar Navigation bei CV und Skills verträgt noch etwas Styling :-)

**CV-Sidebar**
- Die Elemente können etwas schmaler sein (also Höhe reduzieren)
- Die Labels in den Elementen bitte zentrieren. Aktuell sind sie eher gegen oben ausgerichtet
![Auswahl_875](https://user-images.githubusercontent.com/15013947/59845829-97881e80-935e-11e9-9f5d-157832a8b82c.png)

**Skills-Sidebar**
- Die Elemente können etwas schmaler sein (also Höhe reduzieren)
- Die Labels in den Elementen bitte zentrieren. Aktuell sind sie eher gegen oben ausgerichtet
- wenn möglich die Rand-Linien bei "Skills bearbeiten" und "Skill hinzufügen" nicht "durchziehen" (siehe Mockup)
- Ganz allgemein bitte das Label der Kategorie "User Experience Design" auf "UX Design" anpassen

![Auswahl_877](https://user-images.githubusercontent.com/15013947/59845886-b8507400-935e-11e9-9eef-5d9f37434187.png)

Mockup:
![Auswahl_878](https://user-images.githubusercontent.com/15013947/59845940-e1710480-935e-11e9-9715-3667b6252a23.png)

**Comment by TheWalkingLeek** [comment]
improved in 437fef3eeed4883337ec474e67ecb2d45e4a7801
