### ISSUE TITLE
Überarbeitung Skillset Tabelle

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#250]
Bei der Skillset-Tabelle braucht es noch einige Anpassungen/Korrekturen:

**Tabellen-Header:**
- Falsche Font (nicht so gross, bold)
- Header Formatierung bei "Bearbeiten" fehlt
- Bearbeiten Icon zu breite Spalte
- Header muss nicht so hoch sein, Höhe kann sicher um 1/3 reduziert werden
- Allgemein bessere Aufteilung der Spaltenbreite wäre gut
- Bei der letzten Spalte "bearbeiten" zeigt der ganze Klick-Bereich auf "Bearbeiten" und öffnet nicht die View "Members pro Skill"

**Reihenfolge der Spalten anpassen:**
- Skill
- Members
- Kategorie
- Subkategorie
- Default-Set
- Radar
- Portfolio
- "Bearbeiten"

**Skills-Darstellung**
- Skills als "Links" darstellen (blaue Font)
- Bei "Default-Skills" das Puzzle-P Icon
- Bei "Neuen" Skills das grüne "Neu-Icon"

![Skillset-Table](https://user-images.githubusercontent.com/15013947/59847672-70801b80-9363-11e9-933f-6691d0dd6b3a.png)

**Comment by TheWalkingLeek** [comment]
was implemented in 593efbce08719e63f0111e78a20c932681ab4bd2
