### ISSUE TITLE
Styling Skills

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#252]
Die Skill-View hat noch einges an Potential bezüglich Styling.

Ganz allgemein hat es viel zu viel Whitespace. Auch die Fonts sind idR zu gross, zu bold.

* Die Header der Kategorie 1 könnten tiefer sein, mir sind die aktuell etwas zu hoch
* Die Header der Kategorie 2 sollten einiges tiefer sein, mir sind die aktuell viel zu hoch. Auch die Font ist imho zu gross

![Auswahl_888](https://user-images.githubusercontent.com/15013947/59849242-56e0d300-9367-11e9-8143-299d52c4a75b.png)

* Die Font der Skills ist zu gross und zu bold. Siehe auch #251 - dort wäre die Idee, die Skills als Link klickbar zu machen, dann wäre das Styling so oder so anders.
* Auch sonst wäre es gut, wenn noch einiges an Whitespace zwischen den Skill-Einträgen reduziert werden könnte

![Auswahl_883](https://user-images.githubusercontent.com/15013947/59849279-7415a180-9367-11e9-9800-f333935e82fd.png)

**Comment by mzurbuchen** [comment]
https://github.com/puzzle/skills/commit/8df57112925a90beda9c2835231aaf0e254097d2
