### ISSUE TITLE
Skill-Overlay aus Skills-Tab soll nur bewertete Skills anzeigen

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#287]
Wenn ich im Skills-Tab auf einen Skill klicke, wird mir das Overlay mit den Members angezeigt, die diesen Skill haben.
Aktuell erscheinen hier aber auch Members, welche den Skill nicht bewertet haben, das ist falsch. Es sollen nur Members angezeigt werden, die den Skill bewertet haben.
PS: Bei der Skill-Suche funktioniert das.

Overlay mit nicht bewerteten Skills:
![Auswahl_885](https://user-images.githubusercontent.com/15013947/62196039-91358b00-b37d-11e9-9b5b-5974a885d5df.png)

Richtig umgesetzt in Skill-Suche:
![Auswahl_886](https://user-images.githubusercontent.com/15013947/62196076-9eeb1080-b37d-11e9-8889-a3ac9a3cbbe4.png)

**Comment by TheWalkingLeek** [comment]
Implemented in: d666486ca7ac579214edf6198c132097360f6165
