### ISSUE TITLE
Neue Profile werden erst nach Reload angezeigt

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#289]
Wenn ich ein neues Profil erstelle, wird mir das nach dem speichern nicht angezeigt. Ich finde es in der Suche auch nicht.

![Auswahl_887](https://user-images.githubusercontent.com/15013947/62198053-3b62e200-b381-11e9-96c3-776547662a02.png)

![Arbeitsfläche 1_889](https://user-images.githubusercontent.com/15013947/62198066-3ef66900-b381-11e9-9a3f-8579511f464d.png)

Erst nach einem kompletten Reload von PSkills wird finde ich das Profil.

Erwartetes verhalten: Nach dem speichern eines neue Profils, lande ich direkt auf dem CV-Tab des neuen Profils. Das Profil kann zudem ohne manuellen Reload gesucht/gefunden werden.

**Comment by odaner** [comment]
nach keycloak fix glaubs guet.

**Comment by TheWalkingLeek** [comment]
Habe es auch noch einmal durchgetestet und hatte keine Schwierigkeiten... Sollte es wieder auftreten, gerne wieder öffnen.
