### ISSUE TITLE
Skills hinzufügen im Skillset funktioniert teilweise nicht

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#294]
Wenn ich im Skillset via Form einen neuen Skill hinzufüge, dann diesen bearbeite (Default-Set Flag setze), dann speichere übernimmt es die Daten. Bei einem Refresh ist der Eintrag dann aber weg.

Zudem muss man beim Bearbeiten von Skills im Skillset immer 2x auf Speichern klicken damit es den Request absetzt.

**Comment by TheWalkingLeek** [comment]
Wurde in 0c3aeedf8711145d5449ceebf915f4d99fc2d089 als Hotfix gefixt. Lasse das Ticket noch offen, da es noch nicht im master gemerged wurde. #297
