### ISSUE TITLE
Default-Set Checkbox bei "Neuer Skill erstellen" im Skillset

### ISSUE THREAD

**Issue by odaner** [puzzle/skills#295]
Im Form "Neuer Skill erstellen" im Skillset bitte noch die Checkbox "Default-Set" hinzufügen (zu unterst im Form).
Als Admin will im im Skillset gleich bei der Erfassung der Skills angeben, ob es Default ist oder nicht.

![Auswahl_894](https://user-images.githubusercontent.com/15013947/62689522-41814000-b9cb-11e9-96ae-d12ecc7dac42.png)

**Comment by TheWalkingLeek** [comment]
Wurde in 0c3aeedf8711145d5449ceebf915f4d99fc2d089 als Hotfix eingebaut. Lasse das Issue noch offen, da es noch nicht in master gemerged wurde. #298
