### ISSUE TITLE
Same radar and portfolio values in backend & frontend

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/skills#303]
So currently, the possible values for portfolio and radar can be changed using the settings.yml file. Problem is, that this only affects the backend. In the frontend, the values are simply hard-coded: https://github.com/puzzle/skills/blob/6d3dbb8701688560a20b8fa51d2043b022372421/frontend/app/models/skill.js#L23

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
