### ISSUE TITLE
Diverse Bugs in neuer Version

### ISSUE THREAD

**Issue by maederr** [puzzle/skills#305]
- Auf Titelseite fehlen Angaben (Erstellt für, Kontaktperson, E-Mail, Datum, Version)
- Inhaltsverzeichnis erscheint auf Titelseite
- Kapitel 2: Kernkompetenzen --> Tabelle macht nicht Sinn Kategorie --> Notizen

**Comment by odaner** [comment]
Hallo Ramona
Alles "wontfix" da so definiert ;-)
Wir haben uns bewusst enschieden, das "Erstellt für" wegzulassen und das Inhaltsverzeichnis auf die Titelseite zu nehmen.
Die Kernkompetenzen machen durchaus Sinn als Tabelle, wenn dann die Kernkompetenzen vie das neue Skill-Feature definiert wurden ;-)
Daher schliesse ich das Issue als Wontfix.
