### ISSUE TITLE
Fehler beim Hinzufügen neuer Skills

### ISSUE THREAD

**Issue by cboesch-puzzle** [puzzle/skills#308]
Neue Skills können nicht hinzugefügt werden. Man kann den Skill im Textfeld anlegen (siehe 1. Screenshot), aber sobald man Kategorie und Level vergeben hat und den neuen Skill speichern möchte bricht es mit der Fehlermeldung: "Skill muss ausgefüllt werden" ab.

Verwendeter Browser: Firefox Quantum 68.0.2 (64-bit)

**Comment by cboesch-puzzle** [comment]
![Skill_hinzufuegen_1](https://user-images.githubusercontent.com/54942850/64342248-6973bb80-cfea-11e9-9632-418691a97ec2.png)
![Skill_hinzufuegen_2](https://user-images.githubusercontent.com/54942850/64342292-7b555e80-cfea-11e9-880b-a0d421a11cee.png)

**Comment by Robin481** [comment]
Danke fürs Feedback.

Konnte ich in Firefox sowie Chrome noch nicht reproduzieren wird aber aufgenommen.

Könntest du mir noch einen Screenshot der Konsole zukommen lassen wenn dies passiert?

**Comment by cboesch-puzzle** [comment]
![Screenshot from 2019-09-17 14-54-11](https://user-images.githubusercontent.com/54942850/65043534-58686a00-d95b-11e9-9f8c-b3813e73ea41.png)

Ich denke der 422 könnte die Ursache sein. Der Response davon sagt, das irgend ein Feld nicht korrekt ausgefüllt ist, ich glaube das "detail" feld. Dieses sehe ich aber nicht im Dialog. 
Response vom 422: `{"errors":[{"source":{"pointer":"/data/attributes/skill"},"detail":"muss ausgefüllt werden"}]}`

**Comment by Robin481** [comment]
Merci für den Screenshot!
Wir werden dem nachgehen.

**Comment by Kagemaru** [comment]
![New-Skill-Error](https://user-images.githubusercontent.com/12155/68751040-31e44980-0601-11ea-9bac-1be488e7407d.png)

Ich hatte gerade das selbe Problem.
Beim erstellen eines neuen Skills, wird dieser nicht erstellt und meldet danach das Skill ausgefüllt werden muss.

Browser: Firefox 70.0.1 (64-bit)

**Comment by vinzent** [comment]
OS: Fedora 32
Browser: Firefox 76.0.1 (64-bit)

Console:

![skills-xhr-requests](https://user-images.githubusercontent.com/296297/83619379-171cf680-a58c-11ea-99a8-e329328c7d1a.png)

Die 401->422 Sequenz wiederholt sich wenn ich Speichern erneut drücke.

Wenn ich den 422 Request anschaue, ist id=null vom Skill:

![skills-422-fehler-id-null](https://user-images.githubusercontent.com/296297/83619399-1be1aa80-a58c-11ea-88b6-e168def066eb.png)

Ursache dafür ist der 401, weil der Skill dort nicht angelegt werden konnte.

**Comment by vinzent** [comment]
Auch mit Firefox 77.0 (64-bit) auf Fedora 32 besteht das Problem weiterhin.

**Comment by Robin481** [comment]
So ich hatte mal Zeit das Problem anzugehen und konnte es fixxen: https://github.com/puzzle/skills/commit/baf0cd6ff703aeb042d60af26bf99eb25811d144
Normalerweise können User keine Skill erstellen aber von hier natürlich schon. 
Im PuzzleSkills bin ich als Admin eingetragen und hatte natürlich dementsprechend Mühe das zu reproduzieren.

@TheWalkingLeek  ist im Moment noch ziemlich beschäftigt aber auf seinem Zeitplan steht früher :tm:  oder später :tm:  ein Deployment der neuen Skills Features wo dieser Fix auch mitkommen wird :+1:

**Comment by Robin481** [comment]
Bugfix wurde nun mit 4.3.0 deployed. :partying_face:  
Danke für euer Feedback!
