### ISSUE TITLE
Company komplett entfernen

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#326]
Die Seite /companies gibt es immer noch wird aber nicht mehr verwendet. 

Es sollen alle Spuren davon entfernt werden. (Tests, Model, Controller, Routen, Template etc.)

Definition of Done:
Im Code sind keine Spuren der Companies mehr zu finden. (ausser der alten Migration)

**Comment by TheWalkingLeek** [comment]
Fixed in #338
