### ISSUE TITLE
Skillset Read-only for non-admin

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#354]
Currently only Admins can view the Skillset page. 

It should become read-only for all non-admin members. Meaning these non-admin members will be able to view the page but won't be able to edit anything.
For non-admin members there should be a little warning message explaining to them that they aren't able to edit because they are not admin. This should also just be visually implied. (e.g. Buttons greyed out)

**Definition of read-only**
The only thing non-admin users aren't allowed to do is press the edit button (next to the skills) and the new-skill button. All the other functions are allowed (e.g. search and the skills overlay that show all the people that have said skill).

**Be aware**
There are verifications for the admin role happening in the front as well as the back end. Make sure that both ends are covered and can't be accessed through some workaround. 

Definition of Done:
- The Skillset page is now read-only but accessible for non-admin users.
- A little warning message explains the non-admin users that they can't edit. 
- Nothing changes for admin users
- Tests :hatched_chick:

**Comment by Robin481** [comment]
For https://github.com/puzzle/skills/issues/308 we had to allow the users to create skills, for that we just skipped the create call from authorization: https://github.com/puzzle/skills/commit/baf0cd6ff703aeb042d60af26bf99eb25811d144

This needs to be then done smarter here.

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/pull/441

Feature has been implemented, needs to be reviewed and merged. Might need small updates if we update some part of the application before that.

**Comment by lkleisa** [comment]
Is done here: https://github.com/puzzle/skills/pull/495
