### ISSUE TITLE
Readd Company information to people

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#355]
We still want this Dropdown available in person-edit with the same choices available as before but without the whole company model behind it. So a person now will have a text field called: company that will (as before) display: Puzzle ITC, Puzzle ITC Deutschland, Bewerber Partner, EX-Mitarbeiter.
This company information should also show up in the people-list next to everyone's name.

Most important part of this ticket is that a migration that we already added to remove the company now needs to be adaptedto migrate the information from the old system with the company model to the new one with the list of companies in a text field.
Companies can't be added from this dropdown, only over the rails console is enough.

Definition of Done:
- Migration written
- Dropdown available without the whole company model

**Comment by DominikFischli** [comment]
> Dropdown available without the whole company model

As we are using the same model functionality that was present before the company model & so on got removed, I reintroduced this same functionality using that same code (models, controllers etc) in order to adhere to the Rails standard way of doing things.
