### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by psunix** [puzzle/skills#36]
https://travis-ci.org/puzzle/skills

- fix brakeman
- fix rubocop
- add node and frontend tests

**Comment by psunix** [comment]
hab rubocop jetzt mal auf dem masterbranch fixed.
dort kommt jetzt noch ein error bezüglich broccoli.
hab leider keine zeit mehr das genauer anzuschauen heute.

**Comment by mroetheli** [comment]
evtl. Ressourcenproblem
