### ISSUE TITLE
Formularverhalten

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#366]
Nachdem ich die Pflichtfelder ausgefüllt und ein Projekt erfolgreich gespeichert (hinzugefügt) habe, kann das Formular nicht mehr geschlossen werden. Der Speichern & Neu Button funktioniert auch nicht mehr. "Abbrechen" funktioniert nur so lange die Pflichtfelder nicht ausgefüllt wurden.

Nur ein Page-Refresh löste bisher dieses Problem, dass das Formular nicht mehr sichtbar war.

Ich weiss nicht, ob es Browser abhängig ist. Ich verwende Firefox 75 auf einem MacBook.

**Ich würde folgendes neues Verhalten vorschlagen:**
- Formular schliesst nach dem Speichern automatisch. Wenn ich etwas ändern möchte, musst ich zum Eintrag scrollen und dort "bearbeiten" klicken.
- Ein neues leeres Formular kann nur mit dem Button "Speichern & Neu" erstellt werden
- Der Abbrechen Button sollte immer funktionieren. Sobald ich die Pflichtfelder ausgefüllt habe, sollte mich die Applikation beim abbrechen fragen, ob ich die ungespeicherten Änderungen verwerfen möchte.

Ich weiss nicht, ob dieses Verhalten auch bei anderen Formularen in der App so ist.

**Comment by Joshuasony** [comment]
Übrigens bleibt das Formular geöffnet, auch wenn ich zu einem anderen CV wechsle.

**Comment by Robin481** [comment]
Merci für das Feedback! 
Werde schauen das wir es einplanen können.

**Comment by Robin481** [comment]
Dieses Problem scheint mir inzwischen gelöst.
Soviel ich weiss haben wir es nie aktiv gefixt, vermutlich war es ein Browser Problem.
Kannst du @Joshuasony mir auch auf MacOs Seite bestätigen das es nun wie erwartet funktioniert?

**Comment by Joshuasony** [comment]
Yes, funktioniert nun wie erwartet. 👍
