### ISSUE TITLE
Bizarre test behaviour

### ISSUE THREAD

**Issue by Mecanno-man** [puzzle/skills#370]
In the acceptance test "search peopleSkills of JUnit", for some reason trying to select a level higher than 2 results in a lower level being selected than requested. This behaviour is only triggered by the test; running the program and selecting a level manually at the same position poses no problem. My assumption is that the hitbox of the slider is off in the test for some reason.

I'm not sure if this issue is actually fixable in this repo, but @TheWalkingLeek said I should create an issue for this here nonetheless. For now, the workaround is only using levels 1 and 2 in tests.

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
