### ISSUE TITLE
CV Search Jump to Frontend Tests

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/skills#378]
Currently, there are no frontend tests (so none at all) for the "cv search jump to" feature present.
Would be great to add some well covering tests for this feature. Could lead to some challenges since it is depending on render time and things like that

**Comment by Robin481** [comment]
Definition of Done:
- Tests exist for the jump-to feature that work reliably without depending on the timing.

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
