### ISSUE TITLE
Use bootstrap from npm

### ISSUE THREAD

**Issue by topaxi** [puzzle/skills#39]
The only bower dependency we have left is `bootstrap`, since bower is deprecated, it would be nice if we could drop it by moving the `bootstrap` dependency to npm (package.json).

**Comment by SamuelSchwegler** [comment]
Da ich versehentlich auf Uni-Master gepusht habe und danach meine Änderungen in Uni-Master rückgängig gemacht habe lässt sich deleteBower nicht mehr "pull requesten" da die commits bereits im Uni-Master waren. Was kann man da machen?
