### ISSUE TITLE
(3) [Bug] Project Entry Dialog: ESC not only dismisses dropdown (e.g. "Von" Month), but entire dialog

### ISSUE THREAD

**Issue by hellerbarde** [puzzle/skills#392]
Ich habe grad eine Viertelstunde Text für ein Projekt eingetippt und wollte beim Von-Bis-Eingeben das Monats-Dropdown dismissen mit ESC, und dann hat es den gesamten Projekt erfassen Dialog ohne Warnung weggemacht und die Arbeit war weg. 

Ich würde mich über einen entsprechenden "Cancel - Are you sure?"-Dialog freuen. 

EDIT: I changed the title to Bug because in most UI Framework I am aware of, ESC in a dropdown only dismisses the dropdown, and does not interact with the containing Element/Window.

**Comment by Robin481** [comment]
Merci für dein Feedback und sorry für die Umstände.
Wir entwickeln ab Januar wieder am PuzzleSkills weiter, ich nehme dein Feedback für dann gerne in die Planung auf.

**Comment by hellerbarde** [comment]
Cool Danke :)

**Comment by Robin481** [comment]
TODO:
- [ ] Add an overlay that asks to confirm if you really want to stop editing a field if there are unsave changes (doesn't matter if this is coming from an ESC press or pressing the cancel button)
- [ ] Allow the date dropdowns to be closed with ESC without affecting/closing the whole form
- [ ] Write tests for the above feature

**Comment by njaeggi** [comment]
I have added a confirmation Modal when clicking the cancel button in form. I still have to look at the problem with the esc key and fix it. Styling of the new form should also be done too and tests need to be implemented

**Comment by njaeggi** [comment]
This feature is basically implemented, but is blocked by another issues #348, # 349, #350. After those issues are implemented, this issue needs to be tested.

**Comment by Robin481** [comment]
Fixed with the new release, thanks for the issue!
