### ISSUE TITLE
Github PuzzleSkills Showcase

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#393]
Um Interessierten die auf unsere Github Seite stossen ein bisschen etwas vom Tool zu zeigen wäre ein Demo-Gif oder Video sehr cool.

- Abklären was auf Github möglich ist.
- Gif oder Video einbauen (evtl Ordner 'Showcase'?)

**Comment by pSub** [comment]
Ich bin gerade auf das Projekt gestoßen und finde es sehr interessant. Für mich würden schon zwei, drei Screenshots mit wenigen Sätzen ausreichen um einen ersten Eindruck zu gewinnen. Das Ganze lokal aufzusetzen ist für einen ersten Eindruck ziemlich aufwendig.

**Comment by pSub** [comment]
Ich habe es gerade aufgesetzt und mal drei Screenshots gemacht:
![image](https://user-images.githubusercontent.com/83842/178007480-c79aab82-504b-434c-a85f-10f42935c01f.png)
![image](https://user-images.githubusercontent.com/83842/178007581-473b6f4d-8dba-4e8c-a4d8-0a247edb417c.png)
![image](https://user-images.githubusercontent.com/83842/178007685-693bbef6-edbf-46c1-8b7f-98d13f25003c.png)

**Comment by Robin481** [comment]
Hallo @pSub 

Danke für dein Feedback!
Ich bin froh ist es dir gelungen das Projekt reibungslos aufzusetzen und ich danke dir für die Screenshots.
Ende Monat werden wir wieder für einen Moment am PuzzleSkills arbeiten und ich notiere es mir für dann die Screenshots einzubauen und das Showcase damit umzusetzen. 

Cheers

**Comment by pSub** [comment]
Danke für die prompte Reaktion. Ich finde das Projekt bis jetzt super und werbe gerade dafür, dass wir damit unsere Excel Lösung ablösen.

**Comment by Robin481** [comment]
Habe nun ein Showcase Gif hinzugefügt :partying_face:

**Comment by pSub** [comment]
@Robin481 Großartig! :)
