### ISSUE TITLE
Official docker build not working

### ISSUE THREAD

**Issue by andrescarrasco** [puzzle/skills#394]
Hi puzzle team!

I wanted to try out this project, as it is a bit hard to know what it can do. I followed the instructions on https://github.com/puzzle/skills/blob/master/doc/DOCKER.md, but couldn't see a front-end on localhost:8080

are there any missing steps in the instructions?

I also noticed there is only the latest tag in the docker repository, but in the documentation says there should be a stable release too, maybe the latest image is the issue?

**Comment by Robin481** [comment]
Hi @andrescarrasco 

Thanks for the interest in our project.

The docker image is indeed not that well documented yet and lacks some crucial features.

The problem you are facing is, what I'm assuming is the missing Keycloak instance.
As PuzzleSkills' authentication is based on Keycloak it crashes/doesn't work without it. 

We have started integrating a Keycloak instance into the docker compose file, you can find the WIP branch here
https://github.com/puzzle/skills/tree/feature-53173-keyclaok-docker-compose

If you're keen on tinkering around a bit I would recommend you trying to make the Keycloak instance + PuzzleSkills work with the help of that branch. 

I'm sorry that I can't help you more than that for the moment. Improving the Docker Image and adding a DEMO environment is on top of my priority list but I just didn't have time for it yet. I will certainly let you know when there is an update on that front.

All the best

- Robin

**Comment by Robin481** [comment]
Hey @andrescarrasco 
We just merged a new version of the Docker image that comes with a version of Keycloak included. (https://github.com/puzzle/skills/commit/cdd48ea1b0ed4e0c572b9e05fcc9fe49e9761446)

There is sadly some inconsistency across different devices and browsers that we weren't able to iron out. (Follow-Up Issue here: https://github.com/puzzle/skills/issues/439)

If you're still interested in trying out this project I'd recommend you try again with this new Docker Image. I'd be interested to hear how it works on your side.

All the best
- Robin
