### ISSUE TITLE
(1) Fixe Breite für Buttons führen zu hässlichem und unnötigen Text-Umbruch

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#407]
Auf dem Cancel sowie dem Delete Button wird eine fixe Breite von 100px gesetzt, was zu folgendem Verhalten führt.
![grafik](https://user-images.githubusercontent.com/7139459/108674380-7d182800-74e5-11eb-8a69-911b4f0b4fcc.png)

Das ist unnötig, ich würde die manuell gesetzte Breite entfernen. Oder aus welchem Grund wurde diese Breite gesetzt?

**Comment by Joshuasony** [comment]
Habe soeben gesehen, dass die fixe Breite genau in diesem Zusammenhang (Bestätigungsdialog) gesetzt wurde: https://github.com/puzzle/skills/commit/f4c28ad07d02a4f6aa26817816ef17a8739c1d5d#diff-af10a0029d0ec7aae82615f5234345da8aee5b4d402a97d86b8f2bbd1a6993fd. Gibt also wohl keinen Grund, diese fixe Breite zu entfernen.

**Comment by Robin481** [comment]
Merci fürs Feedback @Joshuasony. Ich plane das ein.
