### ISSUE TITLE
Typo "Desing"

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/skills#409]
I guess this is not by desing? :) 
![grafik](https://user-images.githubusercontent.com/7139459/108675311-eba9b580-74e6-11eb-9969-5eb4c64518df.png)

Wenn wir schon dabei sind, bitte "Usability-Testing" mit Bindestrich schreiben. :) Wir haben das soeben bei uns  im Team als default Naming festgelegt.

**Comment by Robin481** [comment]
Typos sind gefixt :)
