### ISSUE TITLE
Sorting while editing

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#419]
The Elements of the profile view are once again being sorted when they are in the process of being edited.

Project example: Have several projects that end after one another. Edit the first project (the most recent one) and change its end date to be earlier than the earliest project. The project will jump out of view as it is now at the bottom of the list.

Hint: This used to be solved with the `volatile: false` parameter. Not sure if this is still used but it could help as a starting point.

Definition of Done:
- [ ] Sorting doesn't happen while editing.
- [ ] A test that tests this use case has been added. (Feature test?)

**Comment by rbotteon** [comment]
The exact same bug affect **Weiterausbildung** and **Stationen** both use @sortByYear("xxxx") for sorting.
**Projekte** uses   @(sortByYear("projects").volatile())

**Comment by MarcEgliP** [comment]
Cannot reproduce anymore 🥳
