### ISSUE TITLE
CV Export - Add company name to filename (1)

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#420]
Currently the filename of the exported cv is like this: `cv_first-name_last-name`
After this ticket it should be: `CV_Puzzle_ITC_first-name_last-name`

Exports happen here [cv.rb](https://github.com/puzzle/skills/blob/master/app/exporters/odt/cv.rb)

Definition of Done:
- New filename naming is implemented
- Tests are adapted

**Comment by marc89763** [comment]
Sehe ich das richtig, dass bisher die CVs so benennt wurden `template_name = "cv_template#{country_suffix}#{anonymous_suffix}.odt"`und nichts mit first-name_last-name? Ich habe jetzt einfach mal den template_name umbenannt.

Zum Punkt _tests are adapted_. Gibt es Tests, welche den CV Export testen? Ich bin alle durchgegangen und habe keinen gesehen.

Momentan funktioniert die CV Export Funktion zudem nicht, vielleicht da wegen einem Problem mit rails `rails db:setup` nicht korrekt funktioniert und man keine Niederlassung auswählen kann beim Export. D.h. ich kann nicht prüfen, ob es die CVs jetzt anders benennt.

**Comment by Robin481** [comment]
Heya @marc89763 
Die Zeile `template_name = "cv_template#{country_suffix}#{anonymous_suffix}.odt"` die du anschaust entscheidet welches Template es verwendet. 
Bsp. Template https://github.com/puzzle/skills/blob/master/lib/templates/cv_template_de_anon.odt wird verwendet wenn der Parameter `country_suffix` = `de` ist und wenn der `anonymous_suffix` = `anon`ist. 
Dies hat also nichts mit dem benennen des Files zu tun das am schluss rauskommt, hier wird nur entschieden welches Template verwendet wird. Den `template_name` musst du entsprechend also auch nicht anpassen.

Der filename wird hier gesetzt: https://github.com/puzzle/skills/blob/f32c88e91aed2e151274aab5cbb646cd3b7aa1d0/app/controllers/concerns/export_controller.rb#L8

Und ja ich denke der Export funktioniert bei dir nicht richtig wenn du keine Niederlassungen hast. Das ganze rails db:setup sollte aber schon funktionieren (ich denke nach deiner Chat-Nachricht heute ist das wohl behoben?)
Ansonsten kanns du auch mit `rails c` in die Konsole gehen und die Niederlassungen von Hand erstellen.
