### ISSUE TITLE
(3)  Extended skills list in CVs

### ISSUE THREAD

**Issue by plow** [puzzle/skills#428]
The skills included in the CV are limited to the core competences. In most cases a CV should contain a list of all relevant skills, not only core competences. Since most users do not declare more than a handfull of skills as core competences, the skills section in the CV often looks empty und incomplete. 

That's why people start to fill extensive technology lists in the notes section which is freetext. Therefore, notes are very individually structured and formatted which is bad if one customer receives multiple CVs from different persons.

I propose the following adjustments:

* Section "Core Competences" is renamed to "Competences"
* Not only skills flaged ad core competence are listed in the CV but all skills with at least professional level experience (3 stars) and a minimal employee interest (2 stars). Ideally these thresholds are configurable by the user or the admins. Core competences can be be rendered in boldface or listed in a seperate row in order to make them more prominent than other skills.

**Comment by Robin481** [comment]
Heya @plow 

Thanks a lot for the extensive Feedback.
It seems very reasonable and I'll add it to the top of the TODO list.

**Comment by Robin481** [comment]
Heya @plow 
Just a little update, we weren't able to plan this with the University Team that currently works on PuzzleSkills.
I'm sorry but I will have to push this back to when we work on PuzzleSkills the next time. I'll let you know once I know more. :v:

**Comment by Robin481** [comment]
We finally might find some time to do this now :) 

TODO: 
- [ ] Add option to CV-Export Interface to include all Skills with a certain SkillLevel or a certain Interest
- [ ] The filtered level is freely configurably by the user via the same inputs as in the skill-search
- [ ] The CV Export handles the core_competences entered by the person who's cv is exported still seperately as they are of special interest to said person. Ideally we would have a row "Kernkompetenzen" and a row "Skills" where the second includes all skills with the in the export window defined rating. I am open to ideas though.
- [ ] Tests 
- [ ] Smoke Tests

**Comment by lkleisa** [comment]
I solved the feature in the linked pull request. Now, you can choose in the cv-export pop up, if you want to include the skills above a specific level of interest. This level is sent to the backend. There, it adds a new table to the cv, if the level is included in the request url. What needs to be done: 
- [ ] Add table to cv (currently, it has the same name as core competences)
- [ ] Testing
- [ ] Smoke testing

**Comment by lkleisa** [comment]
One test in frontend is missing for testing if the right url is generated in person-cv-export.js. For this, we can mock the download service and test, if the file() method is called with right url string
