### ISSUE TITLE
Fix typo "Weiterausbildung"

### ISSUE THREAD

**Issue by dbruegger** [puzzle/skills#430]
In the menu on the left side the link should be "Weiterbildung" instead of "Weiterausbildung".

[skills-menu.pdf](https://github.com/puzzle/skills/files/6181241/skills-menu.pdf)

**Comment by Robin481** [comment]
https://github.com/puzzle/skills/commit/b3a4cf6246dc7d0d9c617291c6eb998d200ff045

**Comment by Robin481** [comment]
Wird beim nächsten Deployment mitgenommen :+1:
