### ISSUE TITLE
picture in new profile

### ISSUE THREAD

**Issue by mroetheli** [puzzle/skills#44]

**Comment by odaner** [comment]
What exactly is the issue? Can you please provide a description?

**Comment by Robin481** [comment]
This is a leftover from back when we worked on the project with the university team.
It's more of a feature request than an issue.
It describes the ability of adding a profile picture from the "person-new" view, instead of only being able to add it retrospectively in the "person-edit" view.

**Comment by Robin481** [comment]
Opening a new Issue for this one
