### ISSUE TITLE
Feature/378 CV search jump to frontend test scroll

### ISSUE THREAD

**Issue by wmvong** [puzzle/skills#449]
Follow-Up to #442 
Right now the tests check if the URL is correct but not whether the page actually scrolls down to the result found in the profiles.
One of the tests should check the windows scroll state.

But checking the windows scroll state like this (https://stackoverflow.com/questions/4096863/how-to-get-and-set-the-current-web-page-scroll-position) seems to always return 0 no matter what.

**Comment by Robin481** [comment]
TODO: 
- [ ] Add scroll state checking functionality to the above mentioned frontend test
- [ ] Make sure the tests still work :grin:

**Comment by lkleisa** [comment]
I found a method for checking the scroll state: `document.documentElement.scrollTop`. I start with the tests but pushed nothing yet. :bird:

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
