### ISSUE TITLE
Weiterbildung hinzufügen ohne Datumsrange nicht mehr möglich

### ISSUE THREAD

**Issue by hupf** [puzzle/skills#450]
## Erwartetes Verhalten

* Ich öffne das CV einer Person
* Ich klicke unter _Weiterbildungen_ auf _Weiterbildung hinzufügen_
* Ich fülle das Formular wiefolgt aus:
![image](https://user-images.githubusercontent.com/66047/117686498-38805c80-b1b7-11eb-9c59-dce9b2465d5f.png)
* Ich klicke auf Speichern.
* Es sollte ein Eintrag hinzugefügt werden mit dem Wert "01.2020" in der ersten Spalte.

## Effektives Verhalten

Nach dem Hinzufügen wird in der Tabelle immer ein Range angezeigt:
![image](https://user-images.githubusercontent.com/66047/117686570-4930d280-b1b7-11eb-84e8-1fc4b6e299bc.png)

Beim Bearbeiten dieses Eintrages wird das _Bis_ auf "heute" gesetzt (die Option "-" lässt sich nicht auswählen, das Select springt zurück auf "heute"):

![image](https://user-images.githubusercontent.com/66047/117686840-88f7ba00-b1b7-11eb-96f3-c820054d87d4.png)

Ich weiss, dass es mal korrekt funktionierte, da ich einen Eintrag habe, bei dem nur ein Jahr angezeigt wird.

**Comment by Robin481** [comment]
Hoi @hupf 
Ich habe mir das nun angeschaut.
Du kannst deine gewünschte Funktionalität erreichen in dem du in den Feldern `von` und `bis` die gleichen Werte einträgst. 
Dann wird es dir nur noch den Wert `01.2020` anzeigen.
Ich bin einverstanden das dies nicht ganz Intuitiv ist. Die Idee dahinter ist das immer entweder der Eintrag noch läuft (also `- heute`) oder das eine Range eingetragen ist.

**Comment by hupf** [comment]
Hey @Robin481 
Danke fürs Abklären. Effektiv, so konnte ich es eingeben.

>  Die Idee dahinter ist das immer entweder der Eintrag noch läuft (also - heute) oder das eine Range eingetragen ist.

Aus der Benutzerperspektive ist es tatsächlich nicht sehr intuitiv, dass es immer ein Range sein muss. Insb. da viele Weiterbildungen einfach eine 1-2 Wöchige Ausbildung mit Zertifikat sind. Da ist relevant, wann das Zertifikat gemacht wurde.

Ich denke, wenn man beim _Bis_ die leere Auswahl (`-`) wählen könnte, wäre das easy (intern könntet ihr ja immer noch den Range mit gleichem Datum speichern).

**Comment by Robin481** [comment]
TODO:
- [ ] Allow `-` selection in dropdown (or `no end` or something, open to fancy wording ideas. We could also just add a checkbox along the lines of `do not set a range` or something.) 
- [ ] This behaves the same way as setting the `end` date as the same value as the `from` date
- [ ] When a daterange that has been set like this is edited again it can show the `to` date as we saved it in the database and doesn't need to display `-` or `kein Ende` (this should make things easier)
- [ ] Write a little test 
- [ ] Smoke test

**Comment by Robin481** [comment]
Fixed with the new release, thanks for the issue!
