### ISSUE TITLE
Error while executing the frontend.

### ISSUE THREAD

**Issue by cyrano007** [puzzle/skills#454]
I have followed the instruction, but with 
npm run start always comes a following error 

`ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
    at /home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js:20:48
    at /home/cyrano/DEV/skills/frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:84:14)
    at sync (/home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/gensync-utils/async.js:66:25)
    at sync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:177:19)
  - code: [undefined]
  - codeFrame: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
  - errorMessage: @ember/test-helpers/-tuple.js: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
        in /home/cyrano/DEV/skills/frontend/node_modules/@ember/test-helpers/addon-test-support
        at broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @ember/test-helpers/-tuple.js
    - line: [undefined]
    - treeDir: /home/cyrano/DEV/skills/frontend/node_modules/@ember/test-helpers/addon-test-support
  - message: @ember/test-helpers/-tuple.js: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
        in /home/cyrano/DEV/skills/frontend/node_modules/@ember/test-helpers/addon-test-support
        at broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers)
  - name: Error
  - nodeAnnotation: Babel: @ember/test-helpers
  - nodeName: broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]
  - originalErrorMessage: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
  - stack: TypeError: [BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/-tuple.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")
    at /home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js:20:48
    at /home/cyrano/DEV/skills/frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:84:14)
    at sync (/home/cyrano/DEV/skills/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/gensync-utils/async.js:66:25)
    at sync (/home/cyrano/DEV/skills/frontend/node_modules/gensync/index.js:177:19)
`
can someone help ?

THX :-)

**Comment by Robin481** [comment]
Hi @cyrano007 
It seems to me like you are stuck trying to start the Frontend server?
Have you read the frontend README? https://github.com/puzzle/skills/blob/master/frontend/README.md
The relevant commands to start the server are listed there.

**Comment by cyrano007** [comment]
Wow, mega fast answer.

yep, that's what I did. i have read the README

The error also comes when I run ember directly.

node v 12.19
ember installed 
yarn install done 
:-(

`ember server --proxy=http://localhost:3000
Proxying to http://localhost:3000
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]) in @ember/test-helpers/application.js

[BABEL] /home/cyrano/DEV/skills/frontend/@ember/test-helpers/application.js: api.assumption is not a function (While processing: "/home/cyrano/DEV/skills/frontend/node_modules/@babel/preset-env/lib/index.js$0")


Stack Trace and Error Report: /tmp/error.dump.f5fbf0f2d1f65d4f204ec734900c1c48.log
`

**Comment by Robin481** [comment]
Haha I have notifications set up on my pc and just couldn't resist answering immediately 😁 
That seems very strange to me. 
Are you on Mac, Windows, or Linux?
If you want to you can post the Stack trace here and I might have time to do some research when I work again on Tuesday :v:

**Comment by cyrano007** [comment]
Nice,
I work with Linux Mint.
I have found the error.
Yarn install overwrites the package.json and changes the ember-cli version. have adjusted it and see it works.
So now I have to push to cloudfoundry and everything is fine.
You can close the issue.
sorry

**Comment by Robin481** [comment]
Glad to hear it worked out :)
