### ISSUE TITLE
Update EmberJS Version

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#480]
We are quite a bit behind now and should probably update the EmberJS version.

As this is hard to plan without knowing what changes in all the different versions this should probably be done in a timeboxed manner for a few versions at a time.

**For now timeboxed to 24 hours**
TODO:
- [x] Update Ember Versions step by step
- [x] Keep #496 in mind as you probably need to update the Node Version along the way anyways.
- [x] Check that in this new state the EmberJS specific security advisories are also fixed
- [x] Upgrade Boostrap to 4 or even 5
- [x] Make sure tests still pass after each step
- [x] Smoke Tests after each step

**Comment by lkleisa** [comment]
Long time ago (today), someone took 16 hours time to upgrade our emberjs frontend. It went well until version 3.28.0.
This ticket was stopped with the result of a new branch (#bla) and an upgrade of emberjs from 3.17.0 to 3.24.0. Node stayed the same on this branch (on the new, there is an upgrade from 12 to 14). 
What I tried after emberjs 3.24.0:
