### ISSUE TITLE
Trying to test skills

### ISSUE THREAD

**Issue by valcriss** [puzzle/skills#507]
I would like to try skills, to see how it works.

My first try was to try the [Run with PostgreSQL](https://github.com/puzzle/skills/blob/master/doc/DOCKER.md#run-with-postgresql) section on the [dockerimage](https://github.com/puzzle/skills/blob/master/doc/DOCKER.md) page

I follow each steps and everythings run fine but at the last step (open http://localhost:8080/ in the browser) i am getting a blank page.

Next i tried the [Run with PostgreSQL and Keycloak](https://github.com/puzzle/skills/blob/master/doc/DOCKER.md#run-with-postgresql-and-keycloak) section 

I follow each steps until the docker-compose up -d command, where the skills_web container dont starts with this error : 

```
! Unable to load application: Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/share/mime/packages/freedesktop.org.xml
2023-02-28 15:17:44 bundler: failed to load command: puma (/app-src/vendor/bundle/ruby/3.2.0/bin/puma)
```

**Comment by Robin481** [comment]
Hello @valcriss 
I am assuming you would just want to run it locally and click around a bit.
The docker approach is not really stable yet as also discussed here https://github.com/puzzle/skills/issues/394
Furthermore we just upgraded our Ruby and Rails versions which seems to be part of your problem.
I would love to improve the docker setup at some point but time is sadly limited.

For now you might be better just following the development setup instructions:
Follow the instructions here to get the backend running: https://github.com/puzzle/skills#prerequisites
And then the frontend instructions here: https://github.com/puzzle/skills/blob/master/frontend/README.md#prerequisites

All the best

Robin

**Comment by valcriss** [comment]
Hi @Robin481 

Unfortunately I'm on windows and the source code approach doesn't work.

I will test via an ubuntu virtual machine.
