### ISSUE TITLE
Acceptance test for generated url on cv export

### ISSUE THREAD

**Issue by lkleisa** [puzzle/skills#511]
In #428, we included skills by a specific level of skill in cv export. Tests are made fully in backend and in ember for the form, but now it would be good, if we have a test, for testing the generated url, which is sent to the rails backend. In `frontend/app/components/person-cv-export.js`, we have generated the url. We add the level of interest in the url and this would be nice to test. The existing tests for the form are in an integration test (person-cv-export-test.js). Now, we need to test the url with an acceptance test in `frontend/tests/acceptance/person-cv-export.js`. There is a todo, what needs to be done

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
