### ISSUE TITLE
Global set ember alerts to closeAfter infinite in tests

### ISSUE THREAD

**Issue by lkleisa** [puzzle/skills#512]
In #497, we wrote a test, that checks if the backend sends an alert for not valid model in create. For no reason, ember displays alerts only one milisec and because of that, the assertion for the text in the alert is always false. Because of that, we've set the closeAfter for the error alert in the `person-new.js` file to infinite (closeAfter: null makes this). This is done here: https://github.com/puzzle/skills/blob/feature/497-email-regex/frontend/app/components/person-new.js#L103. 
It would be nice, if we can set the closeAfter for tests to null globally, becauase we want to test this maybe at another location. Here is an example from someone: https://github.com/adopted-ember-addons/ember-notify/issues/88#issuecomment-386115890

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
