### ISSUE TITLE
Close Forms is not closing down observers

### ISSUE THREAD

**Issue by njaeggi** [puzzle/skills#513]
Currently when you open a form (Education, Project, Advanced Training, Activity), it starts listening to ESC keyup event, when a form is closed, the observer isn't removed because the ember component does not get destroyed. Currently it's fixed with an extra if statement but it would be better to just remove the observer and open it again when opening the form a second time.

To reproduce the bug remove this.displayModal === false from the if statement and open a form twice by clsoing the first one and opening one again, the bug now is that when you have a field selected it will show the confim popup and not leave the field.

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
