### ISSUE TITLE
Dockerize Development Setup

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#515]
Take inspiration here https://github.com/puzzle/cryptopus/blob/master/docker-compose.yml

TODO:
- [x] `docker-compose up` should start all the necessary services
- [x] Make sure to use the correct versions
- [x] README.md is updated

**Comment by MarcEgliP** [comment]
Vorgehen:

- [ ] Mit Docker Setup von Cryptopus vertraut machen
- [ ] Images von der Rails Backend und Ember Frontend erstellen (DB Image schon vorhanden)
- [ ] Compose file erstellen
- [ ] Testen
- Readme anpassen
