### ISSUE TITLE
CV-Search go back behaviour

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#516]
Currently when searching something in the CV-Search, let's say `Rocket Science` and you click on a result in a person's profile you get directed there.
Now pressing the browser back button doesn't lead you back to the CV Search with `Rocket Science` still filled in. It somehow leads puts you on the profile you just found a result in without the query attached.
Furthermore, a renewed press on CV-Search also doesn't contain the last query you searched for.
This makes continuous CV-Search very frustrating as you have to retype the query each time. 

TODO:
- [x] Pressing the browser back button after jumping to a search result should allow you to get back to the CV-Search with your query still present
- [x] Additionally, the query should be somehow saved in the browser so that the user can also just press on the CV-Search again and still have his query entered
- [x] Tests
- [x] Smoke Tests

**Comment by MarcEgliP** [comment]
- [ ] Bug rekonstruieren
- [ ] Component ausfindig machen
- [ ] Problem in Component beheben
- [ ] Feature Smoke Testen
- [ ] Tests für das Feature schreiben
- [ ] Pullrequest stellen
