### ISSUE TITLE
person profile remodel associations (Aktivitäten, Projekte, Weiterbildungen, etc.)

### ISSUE THREAD

**Issue by mroetheli** [puzzle/skills#52]
rename 'Aktivitäten' to 'Stationen' (analogue Mockup, only in frontend template)
inline edit

**Comment by SamuelSchwegler** [comment]
Falls eine neue Weiterbildung/Projekt/Weiterbildung/Station falsch erfasst wird (Bspw keine vierstellige Jahreszahl) wird sie dennoch in der Liste angezeigt. Das Form zum Erstellen bleibt ebenfalls und darauffolgende Änderungen werden direkt in der Liste angepasst.

Falls man nun alle elemente mit education!=null rausfiltert educations-show.js wird sortedEducations bei Änderungen nicht mehr aktualisiert.

Das educationNew lässt sich bei "Abspeichern von falschen Angaben" auch nicht mehr togglen. Man kann diesen Zustand nur verlassen durch verändern und speichern eines Eintrags ohne Fehlermeldungen oder neuladen der Seite.

**Comment by mroetheli** [comment]
cancel, validation do not work as intendet
