### ISSUE TITLE
Do not allow editing or new when other form is already open

### ISSUE THREAD

**Issue by njaeggi** [puzzle/skills#521]
Currently when you have any form open (Activity, AdvancedTraining, Education, Project) then it allows user to open a second form (not the same but for Example when activity form is open you can still open project form. This leads to the bug that you have multiple observers that listen to ESC. 

Which breaks the esc key function and always opens either two confirm dialogs or one from the other form

To fix this, don't allow users to open multiple forms at once

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
