### ISSUE TITLE
False skill count in skillset

### ISSUE THREAD

**Issue by njaeggi** [puzzle/skills#534]
When opening a skill in skillset, the number of people doesn't match the number provided in the title.

![image](https://user-images.githubusercontent.com/68543592/230373227-ab045d90-385d-4217-b926-d69984834bc3.png)

This happens because people that clicked on `nicht bewerten` also count for the amount since they have an associated `peopleSkill` .

We should probably start not including these people.

**Comment by MarcEgliP** [comment]
Vorgehen:

- [ ] Ort finden, wo Memberszahl definiert wird
- [ ] Berechnung berichtigen
- [ ] Tests anpassen / neu schreiben
- [ ] Ausgiebig smoke-testen
- [ ] Draf Pullrequest stellen und von @njaeggi , @lkleisa  oder @kcinay055679 reviewen lassen

**Comment by MarcEgliP** [comment]
![Image](https://user-images.githubusercontent.com/88040929/234034841-77716d56-6633-4be7-8d1a-7f2e78dc6422.png)

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
