### ISSUE TITLE
Error because observer is called before didReceiveAttrs hooks

### ISSUE THREAD

**Issue by lkleisa** [puzzle/skills#535]
Since the emberjs upgrade in #480, there is an error, when you open the skills from a person. The error is `TypeError: this.get(...) is undefined`.
The error is called from an observer function in `new-people-skills-show.js` on line 75. There we get the newPeopleSkills with `this.get("newPeopleSkills")`. The problem is, that we make the set of this attribute in the function `refreshNewPeopleSkills` on line 66, which is called in the didReceiveAttrs hook. So we try to get a value, which is not defined. 

You need to find, why the observer gets called before the hook and how we can fix this.

**Comment by Robin481** [comment]
Irrelevant because of frontend removal
