### ISSUE TITLE
Skills not displayed on the «Skills» page

### ISSUE THREAD

**Issue by hupf** [puzzle/skills#545]
On my profile (personId=205) in the tab «Skills» the count in the heading is 110. But in the list below there are only 38 records shown (yes I am on «All»). There are skills like «Angular» I have rated and where I can find my rating under «Skillset», but the skill ist not listed in my «Skills.

**Comment by Robin481** [comment]
Same as https://github.com/puzzle/skills/issues/546 will be fixed by tomorrow :crossed_fingers:
