### ISSUE TITLE
«Skill Suche» → is it broken? How does it work?

### ISSUE THREAD

**Issue by hupf** [puzzle/skills#546]
Under «Skill Suche», if I select a skill (like «Angular»), no request ist sent and no results are displayed.

Besides that, how does this search UI work? Does it only list the skill ratings with the selected skill level and interest? How can I search for a skill independently of the skill level and interest?

**Comment by Robin481** [comment]
Skills is currently kinda broken, see discussion in #puzzleSkills in our RocketChat :) as soon as i am able to fix the pipeline as well this will be resolved... so hopefully by tomorrow.
