### ISSUE TITLE
Issue during docker compose build - missing npm

### ISSUE THREAD

**Issue by pemorphsm** [puzzle/skills#551]
During `docker compose build` there is an error occuring in step rails 9/12. The reason is a missing npm package.

To fix you need to add the line `RUN apt-get install npm -y` before `RUN npm install -g yarn` in the file `config/docker/development/Rails.dockerfile`

**Comment by Robin481** [comment]
Hello @pemorphsm 

Thanks for the Issue.
We are currently not actively working on this project. However, we might do some big refactoring start of the next year. When that happens we will also go over the installation process again and surely fix this issue as well. I will leave it open until then.

All the best

Robin
