### ISSUE TITLE
Kernkompetenzen not shown on first load of CV page

### ISSUE THREAD

**Issue by m4rc77** [puzzle/skills#561]
The first time when opening a CV e.g. `https://<server>/people/<user-id>` of a member that has skills, that are marked as **Kernkompetenz** they are not shown on the CV page.

Kernkompetenz not shown after first load:
![2024-01-12_11-06](https://github.com/puzzle/skills/assets/19596774/423a11b1-0902-412f-891d-a74002fbb1c8)

After opening the **Skills** page once the skills are then shown properly:
![2024-01-12_11-11](https://github.com/puzzle/skills/assets/19596774/2f01d976-8ee7-4ac2-a9b0-672d34f8bf7b)

**How to reproduce:**
- Add some skills to a member
- Mark at least one skill as Kernkompetenz
- Open the CV page
- Reload the CV page
- boom ... Kernkompetenzen are missing
- go to skills page
- go back to CV page 
- Kernkompetenzen are shown

**Expected behaviour**
- The Kernkompetenzen are always shown on the CV (e.g. directly on the first load)
- If Kernkompetenzen are modified on a 2nd browser window, a reload of the 1st browser window should show the changes accordingly

**Comment by Robin481** [comment]
FYI:
We are removing EmberJS anyways so this will probably just be solved during this process anyway.
Just so you know why your ticket won't be planned into one of our sprints.
