### ISSUE TITLE
Export of skills to CV .odt file should contain the skill level

### ISSUE THREAD

**Issue by m4rc77** [puzzle/skills#562]
When exporting a CV with skills and `Skills nach Level` is chosen e.g as follows:
![2024-01-12_11-20](https://github.com/puzzle/skills/assets/19596774/5eba2ef3-fa93-4b3f-9098-29a9a467bf39)

then the generated .odt file should show/sort the skills by level e.g. as follows:
![2024-01-12_11-32](https://github.com/puzzle/skills/assets/19596774/2913f0d1-6ea7-4c4b-8c76-691262c2f785)

**Requirements**:
- It is possible to determine the level of a given skill on the exported CV
- No empty skill levels should be created (e.g. if there are no skills for level `Professional` then no label `Professional` should be added)
- The sentence `Der Entwickler hat sich selbst als ... eingeschätzt.` should be removed
- All the skills down to the selected level are exported (already the case today)
- The `Kernkompetenzen` should be exported independently of the selected skill level e.g. all of them should be in the exported file (already the case today)

**Comment by Robin481** [comment]
TODO:
- Implement Skills Export as shown in the issue reported
- Adapt tests for that

**Comment by MarcEgliP** [comment]
## Wichtige Dateien für die Umsetzung:

- cv.rb
- people_controller.rb

=> Mit @ManuelMoeri absprechen um Zugriff auf seinen Pullrequest zu erhalten und den Export über die Route
abzugreifen.
