### ISSUE TITLE
New-Skills: Migrate user profile back to Rails 

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#569]
User Profiles should be re-implemented in the Rails application.
For now keep it simple and just re-implement the user view without anything about projects, educations etc.
You can also leave out the language selector if you think it adds too much work.
Editing should already be possible.

TODO:
- Implement the User Profile view and edit in Rails
- For now no Dropdown needed, just access via URL e.g. localhost:3000/users/21
- Tests :partying_face:

**Comment by RandomTannenbaum** [comment]
**Stand 13.02.2024**
Ich habe auf dem branch `feature/569` eine Tabelle erstellt, die erste Userdaten anzeigt. Ausser das habe ich eigentlich noch nicht viel gemacht. Das Styling ist natürlich noch nicht final. Ausserdem sollten die Rollen untereinander und nicht nebeneinander angezeigt werden.

**Comment by RandomTannenbaum** [comment]
- [ ] Altes userprofile ansehen
- [ ] Layout erdenken
- [ ] Wichtigste Profildaten anzeigen
- [ ] Profilbild anzeigen
- [ ] Box für sprachen anzeigen
- [ ] Sprachen anzeigen
- [ ] Bearbeitungsfunktion einführen
- [ ] Smoketests
- [ ] Unit-Tests
- [ ] Review

**Comment by RandomTannenbaum** [comment]
**Stand 16.02.2024**
Die Profilansicht zeigt wieder die wichtigen Informationen des Profils an. Das Darstellen Profildbild funktioniert, aus mir momentan noch unerfindlichen Gründen, noch nicht. Die Sprachen werden grob dargestellt. Ausserdem habe ich angefangen das edit-form einzubauen.

**Comment by RandomTannenbaum** [comment]
**Stand 19.02.2024**
Heute habe ich hauptsächlich die Bearbeitungsfunktion überarbeitet. Die Dropdowns repräsentieren jetzt auch den korrekten Wert, der im Objekt gespeichert ist. Was jetzt noch fehlt ist das hinzufügen von neuen Rollen. Die edit Funktion wir auch noch nicht am korrekten Ort dargestellt, ich habe sie aber zu erarbeitungszwecken noch auf der Übersicht belassen.

Ausserdem habe ich das Übermitteln der Werte noch nicht bearbeitet, was bedeutet, dass hier noch einige Bugs auftreten können. Vorerst will ich aber die Bearbeitungsfunktion finalisieren.

**Comment by RandomTannenbaum** [comment]
**Stand 20.02.2024**
Das Form hat jetzt, bis auf die dynamik beim verkleinern des screens, eine einigermassen angemessene Platzierung. Ich habe das Form nun auch auf die edit Seite verschoben und mit einem Turboframe auf die Übersichtsseite eingebaut.

Das Profilbild wird immer noch nicht richtig angezeigt und man kann es auch noch nicht bearbeiten. Das Bearbeiten der Rollen ist auch noch nicht möglich. Ausserdem haben noch nicht alle dropdowns die korrekte breite.

**Comment by RandomTannenbaum** [comment]
**Stand 26.02.2024**
Heute habe ich angeschaut, wie ich das Form so umbauen kann, dass die Rollen korrekt an das Backend weitergegeben werden. Schlussendlich habe ich das Form auf fields_for umgebaut. Es gibt jedoch noch das Problem, dass ich noch nicht herausgefunden habe, wie ich diese Werte zu den permitted attrs hinzufügen kann. Ich habe einiges ausprobiert, es hat aber noch nicht funktioniert.

**Comment by RandomTannenbaum** [comment]
**Stand 27.02.2024**
Heute habe ich die Logik für die Checkbox eingebaut, die bestimmt ob eine Person eine zweite Nationalität hat. Diese funktioniert jetzt und die zweite Nationalität wird gesetzt oder eben nicht. Des weiteren habe ich das Form responsiver gemacht, so dass die die Tabellen, beim zusammenschieben des Bildschirms, untereinander angezeigt werden.

Ausserdem habe ich angefangen, das dynamische hinzufügen von Rollen zum Profil einzubauen. Hierfür habe ich begonnen, [diesem Tutorial](https://stevepolito.design/blog/create-a-nested-form-in-rails-from-scratch) zu folgen. Ich bin aber noch nicht fertig geworden, und es funktioniert auch noch nicht.

Was noch fehlt:
Bis auf das hinzufügen von Rollen, ist eigentlich alles an Funktionalität vorhanden.

Was das Styling betrifft, fehlen noch kleinere sachen, wie zum Beispiel die Farbe des speicher-buttons. Ausserdem muss ich noch anschauen ob ich das ganze Form etwas schmäler mache, zumal es momentan noch breiter als im laufenden Skills ist

**Comment by RandomTannenbaum** [comment]
**Stand 01.03.2024**
Es sind nun alle grundlegenden Funktionen implementiert und das Styling habe ich auch schon ein wenig angepasst.

Das Styling ist noch nicht final. Ausserdem hat es noch kleinere bugs, wie etwa:
- Das Profilbild wird nach dem Speichern erst nach einem Reload angezeigt
- Das speichern von falschen werten mit anschliessendem Anzeigen der Fehlermeldung führt zu einem Zurücksetzen der 2. Nationalität Checkbox

**Comment by RandomTannenbaum** [comment]
**Stand 05.03.2024**
Zuerst habe ich heute einen Bug behoben, bei dem das Userprofile nach dem Speicher nicht aktualisiert wurde und man noch einmal die Seite neu laden musste.

Ausserdem habe ich das Styling noch ein wenig angepasst und einen template Fehler behoben.

Danach habe ich angefangen mich um Testing zu kümmern. Ich habe mich dabei an den Tests von @MarcEgliP orientiert und so einen ersten erfolgreichen Test geschrieben, der die Integrität der gesamten edit view validiert.

**Comment by RandomTannenbaum** [comment]
**Stand 08.03.2024**
Heute habe ich angenfangen die restlichen Tests zu schreiben. Die Feature-Specs sind meiner Meinung nach fertig. Ich habe noch begonnen einen Controller Test zu schreiben, der noch nicht ganz fertig ist.

Die  View an sich und die Funktionalität ist vorhanden. Vielleicht gibt es noch kleinere Style änderungen oder es werden bugs behoben, wenn diese gefunden werden.

**Comment by RandomTannenbaum** [comment]
**Stand 11.03.2024**
Heute habe ich die letzten Tests geschrieben oder auch aus den alten api tests übernommen und wenn nötig angepasst. Danach habe ich mich noch um einige styling bugs gekümmert.

Das Ticket ist jetzt fast fertig. Es fehlt noch die Übersetzung bei zwei dropdowns, ich habe aber noch nicht genau herausgefunden, wie man das macht.

**Comment by RandomTannenbaum** [comment]
**Stand 12.03.2024**
Das Ticket ist jetzt eigentlich fertig. Es gibt noch einen Edge-Case mit den person-roles, den ich noch resolven muss.
