### ISSUE TITLE
New-Skills: Backup current EmberJS + Rails State on a branch

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#572]
We won't be working on the EmberJS Application anymore.
However, we also don't just want to throw it away. 
Therefore, 
TODO:
- Create a branch with the current state of the main branch and name it appropriately.
- Make a GitHub Release for that last EmberJS state

**Comment by kcinay055679** [comment]
[Branch](https://github.com/puzzle/skills/tree/backup_ember_rails)
[Release](https://github.com/puzzle/skills/releases/tag/v4.4.1)
