### ISSUE TITLE
Fehler beim Export eines CVs

### ISSUE THREAD

**Issue by drnoa** [puzzle/skills#580]
Gemäss Browser Konsole habe ich folgenden Fehler beim Export eines CVs (nicht bei allen, betrifft nur 1 Member). 

/api/people/1428.odt?anon=false&location=4&includeCS=true&skillsByLevel=false:1 
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by Robin481** [comment]
Hello @drnoa 

Thanks for notifying us.

We had the same issue before and the solution was discussed in our internal #puzzleSkills chat. 

Uploading the profile pictures in Chrome seems to cause some weird issues when then trying to export a CV with said picture in it. 
Reuploading the relevant picture from Firefox fixes the issue. 
I did that for the mentioned profile and the export now works as expected.

For documentation's sake I created an issue here as well: https://github.com/puzzle/skills/issues/581

We are currently working on a rather wide-reaching rewrite of PuzzleSkills that will most likely remove the EmberJS frontend, in turn most likely resolving said issue.
