### ISSUE TITLE
Docker-compose failed

### ISSUE THREAD

**Issue by lioram** [puzzle/skills#583]
Hi, I just cloned the repository and when I run the docker-compose build I get this error on the commandline.

> Building rails
Sending build context to Docker daemon  8.192kB
Step 1/19 : FROM ruby:3.2
3.2: Pulling from library/ruby
Digest: sha256:93c3c0d55a9bba1c853c86f3f3eb38b1eaec8b4fe89d491a9fe5d125eeaed4c7
Status: Downloaded newer image for ruby:3.2
 ---> b80e30f08242
Step 2/19 : USER root
 ---> Using cache
 ---> d3fd6723e785
Step 3/19 : ENV RAILS_ENV=development
 ---> Using cache
 ---> a450c4e886b5
Step 4/19 : ENV BUNDLE_PATH=/opt/bundle
 ---> Using cache
 ---> ff336a84bf4a
Step 5/19 : WORKDIR /myapp
 ---> Using cache
 ---> ccb931ed89ef
Step 6/19 : COPY ./rails-entrypoint /usr/local/bin
 ---> Using cache
 ---> 18fd821c6021
Step 7/19 : RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
 ---> Using cache
 ---> ecff06ca4c6b
Step 8/19 : RUN apt-get update
 ---> Running in 317d6d70df44
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
**Err:1 http://deb.debian.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
Err:2 http://deb.debian.org/debian bookworm-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
Reading package lists...
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481**
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
ERROR: Service 'rails' failed to build : Build failed

**Comment by Robin481** [comment]
Heya
The error tells me that you don't have the necessary repository keys to get the sources that it wants to install.
Maybe something like this will do the trick: https://stackoverflow.com/questions/70789307/how-to-fix-the-following-signatures-couldnt-be-verified-because-the-public-key
Might not be the exact issue but you probably just need to add the right keys.
Let me know if this works.
Cheers
Robin

**Comment by Robin481** [comment]
Closed because of inactivity
