### ISSUE TITLE
New-Skills: Allow CV export

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#585]
Implement the CV Export functionality in a Rails view.
Most likely add a button to the Profile view created in #569 
Shouldn't be too much work as all of the export functionality is already implemented in Rails anyways.

TODO:
- Make sure when pressing the button you get the cv as before 
- Allow the same parametes as before
- Make it a modal similar to the old way
- Tests

**Comment by ManuelMoeri** [comment]
**Stand 28.02.2024**
Eine grundsätzliche Version mit einem Modal wurde implementiert. Das Herunterladen wurde getestet und es funktioniert . Die Routes und nötigen Controller wurden erstellt und funktionieren. Das einzige das noch gemacht werden muss ist das Aussehen und Funktionalität des Modals. Es muss auf den richtigen Link mit den richtigen Params redirecten können.

Beispiel für einen Link zum Herunterladen eines CV's:
http://localhost:3000/people/20/export-cv.odt?anon=false&location=1&includeCS=true&skillsByLevel=false

Bei Fragen
- Puzzle Chat
- WhatsApp
- Anrufen
