### ISSUE TITLE
New-Skills: New Dockerfile

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#586]
Move to old Dockerfile somewhere where we can still find it.

Write a new Dockerfile that builds the now just Rails application. 

TODO:
- Write a new Dockerfile that builds the just Rails application
- Optimally without Node (else with the nodesource script)
- Dockerfile is ready for Usage on openshift (not locally)

**Comment by MarcEgliP** [comment]
Hint: https://github.com/puzzle/dockerized-rails-development
The link above can be used if you need help with the docker setup.

**Comment by Robin481** [comment]
I implemented the RubyOps Standard Image and it seems kind of functional already. We'll see on Openshift ✌

**Comment by Robin481** [comment]
Works on Openshift ✅
