### ISSUE TITLE
New-Skills: Skillset edit functionality

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#589]
After #567 Add the ability to edit the Skills that are listed in the skillset.
Orientate yourself on the old functionality of the Ember Application. 

TODO:
- Allow editing of Skills in the Skillset
  - Editing of: Name, Category, Subcategory, Default-Set, Radar, Portfolio, Delete and Save
- Write a end to end test for that

**Comment by MarcEgliP** [comment]
Momentan soll die Edit-Funktionalität so überarbeitet werden, dass wir die Daten direkt im Table selbst bearbeiten können. Dazu sollen die folgenden Tutorials verwendet werden: 

- https://dev.to/software_writer/inline-edits-using-turbo-frames-1l3a
- https://www.youtube.com/watch?v=1WeKlk7GG80

Das Ziel ist es, die Daten der Row als Inline-Form zu bearbeiten.

**Comment by MarcEgliP** [comment]
### STAND 21.02.24 / 12:00 Uhr
Ich habe die Edit Funktionalität so umgebaut, das wir die Row nun direkt inline bearbeiten können, allerdings gibt es noch Probleme mit den Selects: 

Sobald die Kategorie in den Skills neu ausgewählt wird, sollte die Subkategorie gelöscht und die neuen Optionen eingefügt werden, hierzu habe ich noch keinen sauberen Ansatz gefunden.

**Comment by MarcEgliP** [comment]
## Stand 04.03.2024 
Was geht:
- [ ] Editierung funktioniert
- [ ] Speichern funktioniert
- [ ] Errors werden angezeigt

Was noch nicht geht:
- [ ] Ladung des Dropdown mit neuen Optionen bei Select der neuer Parent Category
- [ ] Verhalten wird noch nicht über CRUD-Controller gelöst
