### ISSUE TITLE
New-Skills: Add back the Header of the application

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#602]
Add the old header as it was before the switch. 
![image](https://github.com/puzzle/skills/assets/32168247/2c434790-72b3-4110-8c83-2054def7beb2)

Add all the relevant buttons, if their functionality doesn't exist yet link them to nowhere.

TODO:
- Re-Add the sticky header
- With all the relevant buttons

**Comment by ManuelMoeri** [comment]
**Stand 21.02.2024**

Der sticky header wurde mit allen Buttons und verlinkungen die existieren implementiert. Die Hover-effekte stimmen jedoch noch nicht.

Während dem Daily fragte Päscu mich warum das ich so viel Zeit in das customizen des headers stecke wenn Puzzle Shell genau dies mir abnehmen sollte. Ich sagte das ich den Auftrag habe den alten Header nachzubauen. Er meinte das alle Header von und mit Puzzle Shell möglichst Default mässig implementiert werden sollen. Darum ist dieses Ticket jetzt auf **BLOCKED**. Es muss eine Lösung zu dem Header mit Päscu & Robin gefunden werden.
