### ISSUE TITLE
New-Skills: Re-Add Notizen Members and Kernkompetenzen

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#603]
![image](https://github.com/puzzle/skills/assets/32168247/11832c18-8c7c-4730-939b-33db7c2d7cb5)

Same as in the old application.

Notizen is just a plain text field.
The Kernkompetenzen are chosen in the skills view. (for now just use what is in the database already until we add that functionality)

TODO:
- Allow Notizen to be editable and saved into the database
- Just show the Kernkompetenzen from the seeds. Not yet editable.
- Tests
- :rocket:

**Comment by MarcEgliP** [comment]
## Stand 20.03.2024
- Funktionalität ist implementiert
- Tests geschrieben

TODO:
- [ ] Refactoren, Rails JOINS / ViewHelper verwenden
- [ ] Pipeline fixen
