### ISSUE TITLE
New-Skills: Re-Add Ausbildung 

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#604]
![image](https://github.com/puzzle/skills/assets/32168247/af98826d-96cf-4f10-a967-1fa98ef4ea82)

Like in the old application.

TODO:
- Allow adding of Ausbildungen
- Allow editing of Ausbildungen
- Can be more simple than the old way of just clicking on the elements to edit, but cool if it already works like that.
- Use the daterange partial for this. If the ticket is not ready yet just fake the daterange params and do the rest :) 
- Tests

**Comment by RandomTannenbaum** [comment]
**Stand 27.03.2024**
Ich habe heute die Implementation von @kcinay055679 für die Weiterbildungen übernommen, auf die Ausbildungen umgeschrieben und auch die Tests dazu umgeschrieben.
