### ISSUE TITLE
New-Skills:  Re-Add Stationen

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#606]
![image](https://github.com/puzzle/skills/assets/32168247/5e41ef43-c470-4385-8e85-a152094cec68)

Re-Add Stationen.

Probably very similar to #604 

TODO:
- Allow adding of Weiterbildungen
- Allow editing of Weiterbildungen
- Can be more simple than the old way of just clicking on the elements to edit, but cool if it already works like that.
- Use the daterange partial for this. If the ticket is not ready yet just fake the daterange params and do the rest :) 
- Tests

**Comment by RandomTannenbaum** [comment]
*Stand 16.04.2024*
Ich konnte das gesamte feature mithilfe der Generalisierung von @kcinay055679 implementieren und auch alle tests bis auf einen habe ich schon geschrieben. Einige der Tests sind leider noch flaky, was ich noch fixen muss.
