### ISSUE TITLE
New-Skills: Skillset Show People Modal

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#619]
![image](https://github.com/puzzle/skills/assets/32168247/bd6dc412-f39c-4a16-9254-d724d11e7137)

On the Skillset Page make the Skills Name a Link and when clicked open a modal that then displays all the people having that skill.

TODO:
- Display people when clicking on Skill
- Show their ratings (level and interest) and certificate and competence boolean. Sync with #608 for how to display the bubbles etc. 
- Only show people that have entered a skill level. (because a people skill will exist for all default set skills. There's probably a backend call for that already that you can copy from the api)
- Tests

**Comment by MarcEgliP** [comment]
# Stand 13.03.2024
## What has been done:

- The modal shows up on click of one of the skills inside the skill-list. 
- The basic structure of the modal.

## What has to be done:
- [ ] Use translation to display labels like "interest" or "certificate"
- [ ] If the skill is a default_set the member count inside the modal header should only include the members which have the skills filled out.
- [ ] Discuss styling with @Robin481 
- [ ] Write tests
