### ISSUE TITLE
Visible false test

### ISSUE THREAD

**Issue by MarcEgliP** [puzzle/skills#628]
Inside our feature specs in the people_show_spec.rb file we use the **visible: false** attribute to check whether the modal title appears on the screen after the connected link was clicked. To complete this story you have to remove the **visible: false** attribute from the tests and make them work again. 

**TODO:**
- [ ] Remove visible: false attribute
- [ ] Execute Tests
- [ ] Fix failing ones
- [ ] Create Pullrequest

**What we tried already:**
- Check if we use another browser in the local environment (No we don't)
- Check if there is any difference if we run the test headless or not (Yes, the test works in a headfull environment)
- Disable the animations of all elements and the modal itself (Didn't work either)
- Increase wait time of Capybara (Didn't help)

**Hints:**
- Command to execute the tests: _bundle exec rake_
- Rake seems to not have properly compile the CSS, in turn probably not applying the animation disabling

**Comment by Robin481** [comment]
Fixed in https://github.com/puzzle/skills/commit/f1257df02fb27b509f5eba05b51a3ed28a01e0e1
