### ISSUE TITLE
New-Skills: Re-Add Skill - People Search

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#643]
Basically add the old functionality of searching for people with a certain skill. 
![image](https://github.com/puzzle/skills/assets/32168247/4ee2014d-3fb3-42d2-b920-2f645b4e3ebe)

TODO:
- Allow searching for people with a certain skill
- Default level and interest are 1 (this also means people who didn't fill out the level and interest don't show up here anyways)
- Display the people that match the search criteria and display what the filled out for the relevant people_skills

Stretch Goal:
- Allow searching for multiple skills at the same time like in the old application
- As you are probably able to use some old API functionality this path might just be easier than doing singular search
- Decide for yourself what path you want to take

**Comment by MarcEgliP** [comment]
## TODO:
- [ ] Nur Turbo-Frame bei Search ersetzen
- [ ] Tests schreiben
- [ ] Pullrequest für Review bei @Robin481 freigeben
