### ISSUE TITLE
New-Skills: Add-Person 

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#645]
Add the ability to create a new person, see screenshot of the old application below:

![image](https://github.com/puzzle/skills/assets/32168247/d747bfa3-1776-4cee-859a-ae6e33adf5eb)

TODO:
- Allow creation of new users via button on the start page
- For Languages German, English and French should be set by default (@RandomTannenbaum is the pro here)
- Validations and stuff
- If possible allow picture upload during profile creation (nice to have, not must have)
- Tests

**Comment by RandomTannenbaum** [comment]
**Vorgehen**
- [ ] New View einbauen die Form rendert
- [ ] Button auf übersicht einbauen, der auf new-view führt
- [ ] Fehlermeldungen anzeigen
- [ ] Image-upload
- [ ] Nach Merge des language selectors überprüfen ob die default languages funktionieren
- [ ] Smoke tests
- [ ] Feature specs
- [ ] Review

**Comment by RandomTannenbaum** [comment]
**Stand 12.04.2024**
Ich habe heute das Form überarbeitet. Ausserdem habe ich den image-upload möglich gemacht und das absenden der default-languages implementiert. Somit ist das Form jetzt soweit fertig und ich kann mit den Tests beginnen.

**Comment by RandomTannenbaum** [comment]
**Stand 12.04.2024**
Ich habe heute die Tests geschrieben und kleinere Bugs gefixt. Ich habe in den Tests bei button-clicks manchmal noch flaky Verhalten festgestellt, das sich mir noch nicht ganz erschliesst und dem ich noch auf den Grund gehen werde.
