### ISSUE TITLE
New-Skills: Re-Add CV-Search

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#652]
Free-Text search like it was in the old application.
Most code should already exist as this was done in the api anyway.

![image](https://github.com/puzzle/skills/assets/32168247/738eee25-33ee-402c-bcbf-2e5563fe7045)

TODO:
- Do it :wink: 
- Searches through all content of the profiles
- Displays a link that jumps to the relevant place in the profile
- Tests

**Comment by RandomTannenbaum** [comment]
**Vorgehen**
- [ ] Alte search anschauen um zu sehen wie sie funktioniert
- [ ] Neue view für search erstellen mit (noch) nicht funktionaler search-bar
- [ ] Neuen controller erstellen und herausfinden was man aus dem alten controller übernehmen kann
- [ ] Ergebnisse nur mit Link auf Profil anzeigen
- [ ] Jump-to funktionalität einbauen
- [ ] Specs & smoke-tests
- [ ] Review

**Comment by RandomTannenbaum** [comment]
**Stand 18.04.2024**
Ich habe heute alten controller genommen und auf eine auch neu erstellte view angepasst. Ausserdem habe ich schon eine einfache Suchfunktionalität eingebaut und die Ergebnisse wie im alten Skills gestyled.

**Comment by RandomTannenbaum** [comment]
*Stand 19.04.2024*
Ich habe heute das gesamte Styling der Search-Results vorgenommen. Ausserdem habe ich mich mit pg-search auseinandergesetzt um ein Problem zu beheben, durch das nil Resultate zurückgegeben wurden. Ich habe schliesslich die nil Werte herausgefiltert.

**Comment by RandomTannenbaum** [comment]
**Stand 22.04.2024**
Heute habe ich die Jump-To Funktion eingebaut und angefangen Tests zu schreiben
