### ISSUE TITLE
Skillset - Users-with-skill modal doesn't close correctly after navigation

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/skills#673]
On the Skillset page we can click on the name of any skill, which then opens a modal that shows every user that has that skill. 

![image](https://github.com/puzzle/skills/assets/109959802/62725d8a-39f4-418c-b258-42c5fe92f30b)

The names of these users are hyperlinks, which allows us to get directly to the user-profile.

![image](https://github.com/puzzle/skills/assets/109959802/d65da0d6-2b46-4c84-a227-cd60367bc5fc)

If we then use the browsers navigate-back function and proceed to close the modal, it doesnt close correctly.

![image](https://github.com/puzzle/skills/assets/109959802/29dcc2e9-64bf-4e31-a8b5-3ed4cf59efad)

The modal backdrop seems to stay on the page and we also cant click anything in the background.

**Comment by MarcEgliP** [comment]
## Stand: 01.05.2024
Wurde gefixed muss aber noch mit @Robin481 besprochen werden, ob das jetzige Verhalten so gemerged werden kann.
