### ISSUE TITLE
CSS "Bughunt"

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#691]
There are quite a few places where the CSS subtly breaks.
Look through the application and fix such small but annoying errors.
Or comment them here to keep track of them. 
Furthermore, look at the old application and see if there are big differences leftover that we can adapt so it looks more close to the old application. 

Timebox 2h

**Comment by Robin481** [comment]
![image](https://github.com/puzzle/skills/assets/32168247/9875050c-c2d6-4fe7-9ea9-d202cc6a98e4)
Skillset stays selected even though we are not on that page

**Comment by Robin481** [comment]
![image](https://github.com/puzzle/skills/assets/32168247/d44c3140-cef7-4654-8798-55a32c20ad3c)

Add some spacing between the boxes

**Comment by ManuelMoeri** [comment]
![image](https://github.com/puzzle/skills/assets/109959820/b9f505d0-3e59-41f5-9616-63a022a8aab2)

Name of currently logged in person should not have the link styling but should rather have the same color as "admin".

**Comment by ManuelMoeri** [comment]
Space between tab and sidepanel component is not the same when scrolling

Before scrolling
![image](https://github.com/puzzle/skills/assets/109959820/a70d212e-6ebc-4b11-9b1e-7b60018da6c8)

After srolling
![image](https://github.com/puzzle/skills/assets/109959820/a4ebfa0b-9998-4b4a-b078-58514285c29b)
