### ISSUE TITLE
Fix scrolling behaviour of side menu in userprofile

### ISSUE THREAD

**Issue by MarcEgliP** [puzzle/skills#692]
If I navigate to a users profile and want to use the sidemenu, the behaviour of it is not yet the same as in the old skills. Instead of scrolling only the content it should be possible to scroll the content with the sidebar of the entire page. Also if the page is very small, two sidebars appear on the page where it should be only one to scroll the profile content.

TODO:
- [x] Enable scrolling with entire page instead of min-height scrollbar
- [x] Check that the page doesn't display two scrollbars when the window gets too small
- [x] Make Unit test adjustments if necessary

**Comment by ManuelMoeri** [comment]
ToDO on 22.05.24:
- [ ] Fix scrolling behaviour of "Skills bearbeiten" & "Skill hinzufügen"
- [ ] Fix appearing of content when already scrolled out of render
- [ ] Possibly fix focus css bug when clicking on a element that is placed above the current position
