### ISSUE TITLE
Re-Add Skills Scroll-To Menu

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#693]
Here we added it to the user profile: https://github.com/puzzle/skills/issues/667

Also add it to the user's skill view :grin: 

![image](https://github.com/puzzle/skills/assets/32168247/a3cde4f2-ea02-443e-b9a4-39d799eae9e2)

Also please change the buttons to look more like in the above screenshot. 

TODO:
- Add the same scroll to menu to the user skills
- Change button positions
- Tests and stuff
- :rock:

**Comment by MarcEgliP** [comment]
On hold, since I have to discuss the scrolling behaviour with @Robin481
